
// Dicionários simulados para o sistema de filtragem.
// Em um sistema real, estes seriam arquivos JSON ou bancos de dados carregados via API.

export const MOCK_PT_DICT = new Set([
  'casa', 'vida', 'amor', 'bola', 'pato', 'gato', 'mesa', 'faca', 'neto', 'loja', 
  'site', 'web', 'hoje', 'bom', 'mau', 'sim', 'nao', 'festa', 'carro', 'moto',
  'sol', 'lua', 'mar', 'ceu', 'flor', 'luz', 'paz', 'som', 'cor', 'dor', 'filme',
  'livro', 'papel', 'caneta', 'lapis', 'borracha', 'escola', 'aula', 'aluno',
  'amigo', 'futebol', 'brasil', 'musica', 'video', 'jogo', 'arte', 'saude',
  'pedra', 'ouro', 'prata', 'bronze', 'ferro', 'aco', 'madeira', 'vidro'
]);

export const MOCK_EN_DICT = new Set([
  'home', 'life', 'love', 'ball', 'duck', 'cat', 'dog', 'table', 'knife', 'shop',
  'site', 'web', 'today', 'good', 'bad', 'yes', 'no', 'party', 'car', 'bike',
  'sun', 'moon', 'sea', 'sky', 'flower', 'light', 'peace', 'sound', 'color',
  'pain', 'book', 'paper', 'pen', 'pencil', 'rubber', 'school', 'class', 
  'friend', 'soccer', 'brazil', 'music', 'video', 'game', 'art', 'health',
  'stone', 'gold', 'silver', 'bronze', 'iron', 'steel', 'wood', 'glass',
  'cloud', 'tech', 'soft', 'hard', 'data', 'code', 'link', 'net'
]);

export const MOCK_CITIES = new Set([
  'saopaulo', 'rio', 'curitiba', 'salvador', 'recife', 'manaus', 'fortaleza',
  'brasilia', 'belem', 'goiania', 'campinas', 'santos', 'natal', 'palmas',
  'portoalegre', 'florianopolis', 'vitoria', 'maceio', 'teresina', 'joaopessoa'
]);

export const MOCK_ANIMALS = new Set([
  'gato', 'cachorro', 'papagaio', 'leao', 'tigre', 'urso', 'macaco', 'zebra',
  'girafa', 'elefante', 'cobra', 'lagarto', 'peixe', 'tubarao', 'baleia',
  'lobo', 'raposa', 'coelho', 'rato', 'cavalo', 'vaca', 'porco', 'galinha'
]);

export const MOCK_NAMES = new Set([
  'joao', 'maria', 'jose', 'ana', 'pedro', 'paulo', 'lucas', 'julia', 'marcos',
  'felipe', 'rafael', 'bruna', 'carla', 'fernanda', 'gabriel', 'daniel',
  'thiago', 'bruno', 'vitor', 'igor', 'caio', 'andre', 'luiz', 'ricardo',
  'beatriz', 'camila', 'leticia', 'amanda', 'larissa', 'patricia', 'aline',
  'enzo', 'valentina', 'arthur', 'miguel', 'heitor', 'theo', 'davi', 'bernardo'
]);

export const MOCK_SURNAMES = new Set([
  // Origem Portuguesa/Brasileira (Expandida)
  'silva', 'santos', 'oliveira', 'souza', 'rodrigues', 'ferreira', 'alves', 'pereira', 'lima', 'gomes',
  'costa', 'ribeiro', 'martins', 'carvalho', 'almeida', 'lopes', 'soares', 'fernandes', 'vieira', 'barbosa',
  'rocha', 'dias', 'nascimento', 'andrade', 'moreira', 'nunes', 'marques', 'machado', 'mendes', 'freitas',
  'cardoso', 'ramos', 'santana', 'teixeira', 'medeiros', 'batista', 'macedo', 'cavalcante', 'figueiredo', 'melo',
  'pontes', 'correia', 'rezende', 'guimaraes', 'farias', 'aranha', 'borges', 'monteiro', 'paiva', 'castro',
  'camargo', 'barros', 'correa', 'fonseca', 'viana', 'vianna', 'franco', 'silveira', 'moraes', 'peixoto',
  'assis', 'braganca', 'muniz', 'padilha', 'duarte', 'bernardes', 'portela', 'caldeira', 'aguiar', 'abreu',
  'amaral', 'amorim', 'antunes', 'aragao', 'araujo', 'assuncao', 'azevedo', 'bacelar', 'bahiana', 'baltazar',
  'bandeira', 'barreto', 'bezerra', 'bittencourt', 'blanco', 'boaventura', 'bonfim', 'braga', 'brandao', 'brito',
  'cabral', 'caetano', 'caldas', 'caminha', 'campos', 'canedo', 'capistrano', 'carneiro', 'casagrande', 'castelo',
  'chaves', 'coelho', 'coimbra', 'colaco', 'conde', 'cordeiro', 'coutinho', 'cruz', 'cunha', 'dantas',
  'delgado', 'drumond', 'escobar', 'espindola', 'esteves', 'evangelista', 'fagundes', 'falcao', 'feitosa', 'felicio',
  'felix', 'ferraz', 'fialho', 'fontes', 'fortes', 'fragoso', 'franca', 'freire', 'frota', 'furtado',
  'galvao', 'garcia', 'garces', 'gaspar', 'gentil', 'gouveia', 'guerra', 'gusmao', 'heliodoro', 'henriques',
  'holanda', 'horta', 'ibiapina', 'inacio', 'jardim', 'jurema', 'lacerda', 'lages', 'laranjeira', 'leal',
  'leite', 'lemos', 'lins', 'linhares', 'lisboa', 'lobato', 'lousada', 'loyola', 'lucena', 'luz',
  'lyra', 'magalhaes', 'maia', 'malta', 'maranhao', 'marcondes', 'marinho', 'marins', 'mattos', 'matos',
  'meireles', 'meirelles', 'mesquita', 'miranda', 'montenegro', 'morais', 'mota', 'motta', 'moura', 'munhoz',
  'negrao', 'neves', 'nobrega', 'nogueira', 'noronha', 'oliva', 'ornellas', 'otoni', 'pacheco', 'paes',
  'paim', 'paixao', 'pantoja', 'paranhos', 'parreiras', 'paschoal', 'passos', 'pecanha', 'pedroso', 'penteado',
  'perdigao', 'pimenta', 'pimentel', 'pinheiro', 'pinto', 'pires', 'piza', 'porto', 'prado', 'queiroz',
  'quintanilha', 'rangel', 'raposo', 'reboucas', 'rego', 'reis', 'rios', 'robledo', 'rollemberg', 'romano',
  'rosa', 'rosas', 'roure', 'sampaio', 'sanches', 'saraiva', 'sardenberg', 'sarmento', 'schimidt', 'seixas',
  'serpa', 'siqueira', 'sodre', 'taborda', 'tahan', 'tavares', 'tavora', 'teles', 'toledo', 'tolentino',
  'torquato', 'torres', 'trigueiro', 'trindade', 'uchoa', 'valadao', 'valente', 'valois', 'vargas', 'vasconcelos',
  'vasques', 'vaz', 'veiga', 'veloso', 'vellozo', 'vergueiro', 'veras', 'vidal', 'vilaca', 'vilasboas',
  'villela', 'xavier', 'zago', 'abravanel', 'accoioly', 'adorno', 'albuquerque', 'alcantara', 'aleixo', 'amarante', 'anchieta',
  'anjos', 'antes', 'aquino', 'arantes', 'arao', 'arbos', 'arieta', 'arrais', 'arruda', 'avila', 'balduino',
  'beira', 'belfort', 'belo', 'beltrao', 'berenguer', 'bicalho', 'bispo', 'boas', 'borba', 'botelho', 'burlamaqui',
  'caires', 'cajado', 'calheiros', 'canavarro', 'capanema', 'capucho', 'carneiro', 'carrilho', 'cavalcante', 'cerqueira',
  'cesar', 'cipriano', 'coronel', 'corte', 'covas', 'crivelari', 'curado', 'custodio', 'damasceno', 'dornelles', 'eirado',
  'epitacio', 'eugenio', 'eustaquio', 'faustino', 'ferreiras', 'fogaça', 'fontoura', 'frutuoso', 'furtado', 'galante',
  'galindo', 'galvao', 'gama', 'gatto', 'geraldo', 'gil', 'godoy', 'goncalves', 'gouvea', 'gramacho', 'grangeiro',
  'grego', 'guarda', 'guedes', 'herculano', 'hipolito', 'humberto', 'italo', 'jacobina', 'jacinto', 'jaques', 'junqueira',
  'justino', 'kreisler', 'labatut', 'lamarca', 'lamego', 'landim', 'lavoier', 'lazaro', 'leitao', 'leonardo', 'leoncio',
  'loiola', 'longo', 'loreto', 'loureiro', 'lourenço', 'lucas', 'luciano', 'mabilia', 'maciel', 'madruga', 'magalhaes',
  'mainardi', 'malafaia', 'maldonado', 'mancebo', 'mangabeira', 'manhães', 'manso', 'mantovani', 'marques', 'masson',
  'mauricio', 'maximo', 'mello', 'meneses', 'menezes', 'mercante', 'messias', 'miguel', 'milhomens', 'militão', 'moura',
  'mussolini', 'nadal', 'nakamura', 'narciso', 'navarro', 'netto', 'neiva', 'nobre', 'nolasco', 'novais', 'novaess',
  'offredi', 'olaio', 'oliva', 'onofre', 'osorio', 'otavio', 'pacifico', 'paoli', 'parente', 'parra', 'pastor', 'patricio',
  'paulino', 'pavani', 'paz', 'peçanha', 'pechincha', 'pedreira', 'pedrosa', 'peixoto', 'penido', 'penna', 'peralta',
  'perazzo', 'peron', 'pessoa', 'picanco', 'picheth', 'pilar', 'pina', 'pinder', 'pinto', 'piovesan', 'piragibe',
  'pitanga', 'poças', 'poli', 'polvora', 'pompeu', 'ponte', 'portugal', 'povoas', 'praciano', 'prates', 'puga',
  'quadros', 'quaresma', 'queiroga', 'queiroz', 'quintal', 'quintela', 'rabello', 'ramalho', 'ranieri', 'rebelo',
  'rebocho', 'regis', 'regueira', 'reinaldo', 'remedio', 'renault', 'ressurreicao', 'ribeiro', 'ribas', 'ricardo',
  'rinaldi', 'rios', 'rivas', 'rizzo', 'robalinho', 'rocha', 'roquete', 'rossi', 'sa', 'sabino', 'sacramento', 'salazar',
  'salgado', 'salomao', 'salvador', 'salviano', 'sampaio', 'samuel', 'sangalo', 'sansone', 'santoro', 'sapucaia', 'saravia',
  'sarney', 'scalla', 'senna', 'serafim', 'serra', 'servulo', 'severo', 'shimada', 'silva', 'silveira', 'simas', 'simoes',
  'siola', 'siqueira', 'siriani', 'sobreira', 'sobrito', 'sola', 'soler', 'soncini', 'soriano', 'sousa', 'spinelli',
  'stefano', 'suzano', 'tabosa', 'tagliaferro', 'talento', 'tancredo', 'tavares', 'teixeira', 'telmo', 'temer', 'tenorio',
  'terceiro', 'thome', 'tiburcio', 'tito', 'tobias', 'tolosa', 'toledo', 'tonelli', 'torres', 'tourinho', 'travassos',
  'trentini', 'trindade', 'turco', 'uchoa', 'ulhoa', 'urbano', 'urquiza', 'vaca', 'valadão', 'valença', 'valim',
  'valverde', 'varela', 'vargas', 'vasques', 'vaz', 'veloso', 'venancio', 'ventura', 'vergueiro', 'vespasiano', 'viana',
  'vidal', 'viegas', 'vieira', 'vilas', 'villeneuve', 'villas', 'vinhadel', 'virgulino', 'vitoria', 'vital', 'vivan',
  'xavier', 'yunes', 'zamboni', 'zanella', 'zanini', 'zanzini', 'zattar', 'zeferino', 'zenha', 'zerbini', 'zonta',
  // Origem Italiana
  'rossi', 'ferrari', 'esposito', 'bianchi', 'romano', 'colombo', 'ricci', 'marino', 'greco', 'bruno',
  'gallo', 'conti', 'de luca', 'mancini', 'costa', 'giordano', 'rizzo', 'lombardi', 'moretti', 'barbieri',
  'fontana', 'santoro', 'mariani', 'ferrara', 'gallari', 'amato', 'bellini', 'basile', 'riva', 'donati',
  'pellegrini', 'caruso', 'pagano', 'vitali', 'fabbri', 'd angelo', 'gatti', 'giuliani', 'serra', 'conte',
  'palumbo', 'gentile', 'marchetti', 'ferretti', 'martini', 'sorrentino', 'carbone', 'mazza', 'farina', 'orsini',
  'valente', 'caputo', 'ferraro', 'guerra', 'longo', 'fiori', 'ottaviani', 'neri', 'grasso', 'piazza',
  'valentini', 'messina', 'monti', 'd amico', 'parisi', 'marchi', 'villa', 'foti', 'marini', 'molinari',
  'morelli', 'de rosa', 'ferrario', 'biondi', 'castelli', 'bernardi', 'de santis', 'stefani', 'manzoni', 'bonini',
  'silvestri', 'grimaldi', 'tosi', 'damico', 'pellegrino', 'carli', 'massa', 'moro', 'rossini', 'guidi',
  'rizzi', 'benedetti', 'zanetti', 'milani', 'donati', 'patti', 'piras', 'salvatore', 'sorrento', 'verga',
  // Origem Alemã
  'muller', 'schmidt', 'schneider', 'fischer', 'weber', 'meyer', 'wagner', 'becker', 'schulz', 'hoffmann',
  'schaffer', 'koch', 'bauer', 'richter', 'klein', 'wolf', 'schroder', 'neumann', 'schwarz', 'zimmermann',
  'braun', 'krueger', 'hartmann', 'lange', 'schmitt', 'werner', 'schmitz', 'krause', 'meier', 'lehmann',
  'schmid', 'herrmann', 'maier', 'mayer', 'walter', 'kohler', 'huber', 'kaiser', 'fuchs', 'peters',
  'scholz', 'weiss', 'jung', 'hahn', 'schubert', 'vogel', 'friedrich', 'guenther', 'eichhorn', 'beck',
  'keller', 'winkler', 'frank', 'roth', 'albrecht', 'ludwig', 'boehm', 'schuster', 'kraus', 'ziegler',
  'haas', 'schumacher', 'arnold', 'wiedemann', 'otto', 'graf', 'krauss', 'vogel', 'stein', 'jaeger',
  'busch', 'horn', 'brandt', 'sauer', 'seidel', 'ernst', 'dietrich', 'pohl', 'fiedler', 'kuhn',
  'bergmann', 'thomas', 'voigt', 'otto', 'gertner', 'schreiber', 'lorenz', 'baumann', 'ziegler', 'kramer',
  // Origem Espanhola
  'garcia', 'rodriguez', 'gonzalez', 'fernandez', 'lopez', 'martinez', 'sanchez', 'perez', 'gomez', 'martin',
  'jimenez', 'ruiz', 'hernandez', 'diaz', 'moreno', 'muñoz', 'alvarez', 'romero', 'alonso', 'gutierrez',
  'navarro', 'torres', 'dominguez', 'vazquez', 'ramos', 'gil', 'ramirez', 'serrano', 'blanco', 'molina',
  'morales', 'suarez', 'ortega', 'delgado', 'castro', 'ortiz', 'rubio', 'marin', 'sanz', 'nuñez',
  'iglesias', 'medina', 'cortes', 'castillo', 'garrido', 'santos', 'guerrero', 'cano', 'prieto', 'mendez',
  'cruz', 'calvo', 'gallego', 'vidal', 'leon', 'herrera', 'marquez', 'peña', 'flores', 'cabrera',
  'campos', 'vega', 'fuentes', 'carrasco', 'diez', 'caballero', 'reyes', 'nieto', 'aguilar', 'pascual',
  'santana', 'herrero', 'lorenzo', 'montero', 'hidalgo', 'gimenez', 'ibañez', 'ferrer', 'duran', 'santiago',
  'benitez', 'mora', 'vicente', 'vargas', 'arias', 'carmona', 'crespo', 'roman', 'pastor', 'soto',
  // Origem Japonesa
  'sato', 'suzuki', 'takahashi', 'tanaka', 'watanabe', 'ito', 'yamamoto', 'nakamura', 'kobayashi', 'kato',
  'yoshida', 'yamada', 'sasaki', 'yamaguchi', 'saito', 'matsumoto', 'inoue', 'kimura', 'hayashi', 'shimizu',
  'yamazaki', 'nakajima', 'ikeda', 'abe', 'hashimoto', 'yamashita', 'ishikawa', 'nakagawa', 'maeda', 'fujita',
  'okada', 'goto', 'hasegawa', 'ishii', 'murakami', 'kondo', 'sakamoto', 'endo', 'aoki', 'fujii',
  'nishimura', 'fukuda', 'ohta', 'miura', 'fujiwara', 'okamoto', 'matsuda', 'nakano', 'nakagawa', 'ono',
  'tamura', 'takeuchi', 'kaneko', 'wada', 'nakayama', 'ishida', 'ueda', 'morita', 'hara', 'shibata',
  'sakai', 'kudoh', 'yokoyama', 'miyazaki', 'miyamoto', 'uchida', 'takagi', 'ando', 'taniguchi', 'ohno',
  'maruyama', 'imai', 'takada', 'fujimoto', 'murata', 'takeda', 'ueno', 'sugiyama', 'masuda', 'sugawara',
  'hirano', 'kojima', 'oyama', 'kubo', 'matsui', 'iwasaki', 'sakurai', 'kinoshita', 'noguchi', 'matsuo',
  'nomura', 'kikuchi', 'sano', 'onishi', 'sugimoto', 'arai', 'narita', 'kano', 'matsushita', 'yoshikawa',
  // Origem Árabe/Libanesa
  'haddad', 'mansour', 'nassar', 'saad', 'malouf', 'jabbour', 'khoury', 'farah', 'salem', 'antoun',
  'daher', 'moussa', 'tannous', 'rizk', 'ghanem', 'ayoub', 'eid', 'sarkis', 'khalil', 'abboud',
  'younes', 'nammour', 'harb', 'sleiman', 'atallah', 'matar', 'chaer', 'boueri', 'abdo', 'saliba',
  'najjar', 'azzam', 'fadel', 'hakim', 'hamad', 'kassis', 'madi', 'rahal', 'sayegh', 'zein',
  'aboud', 'alam', 'amin', 'assaf', 'badawi', 'darwish', 'fakhoury', 'ghazal', 'habib', 'halabi',
  'hashem', 'idriss', 'ismail', 'jaber', 'karam', 'khatib', 'mahfouz', 'merhi', 'mounir', 'nasr',
  'qasim', 'rashid', 'saab', 'sabbagh', 'saleh', 'shahin', 'taleb', 'wahba', 'yaghi', 'zaiter',
  // Adicionais diversos para volume
  'abadi', 'abreu', 'accorsi', 'acker', 'adams', 'affonso', 'agostini', 'aguiar', 'ahmed', 'aiello',
  'alberti', 'albrecht', 'albuquerque', 'alcantara', 'alencar', 'alexandre', 'alfieri', 'almeida', 'alonso', 'altieri',
  'alvarez', 'alves', 'amado', 'amaral', 'ambrosio', 'amorim', 'anchieta', 'anderson', 'andrade', 'andres',
  'angeli', 'anjos', 'antunes', 'aquino', 'aragon', 'arantes', 'araujo', 'arce', 'arcieri', 'ardito',
  'areias', 'arena', 'argolo', 'arias', 'arieta', 'arrais', 'arruda', 'asfora', 'assad', 'assuncao',
  'atala', 'augusto', 'avila', 'azevedo', 'bach', 'bacelar', 'badra', 'baeta', 'baggio', 'bahia',
  'balbi', 'baldan', 'balduino', 'ballester', 'bandeira', 'baptista', 'barata', 'barbieri', 'barbosa', 'barcelos',
  'barone', 'barreto', 'barros', 'barroso', 'basile', 'bastos', 'batista', 'bauer', 'becker', 'belchior',
  'belfort', 'bellini', 'belo', 'beltrao', 'benedetti', 'benites', 'benjamin', 'bento', 'berardi', 'berenguer',
  'bernardi', 'bernardo', 'bertani', 'berti', 'bertoli', 'bezerra', 'bianchi', 'bicalho', 'bidu', 'bieber',
  'binotto', 'bispo', 'bittar', 'bittencourt', 'blanco', 'boas', 'boaventura', 'bocaiuva', 'boff', 'boghosian',
  'bolivar', 'bonadio', 'bonfim', 'bonini', 'borba', 'borges', 'borghi', 'bororo', 'botelho', 'botura',
  'braga', 'braganca', 'brandao', 'brasil', 'braun', 'brito', 'brizola', 'brochi', 'brum', 'bruno',
  'buarque', 'bueno', 'bugni', 'bulhoes', 'burlamaqui', 'burnier', 'busato', 'busch', 'cabral', 'cacace',
  'caceres', 'caetano', 'caires', 'cajado', 'calado', 'calazans', 'caldas', 'caldeira', 'calheiros', 'calmon',
  'camacho', 'camara', 'camargo', 'camelo', 'caminha', 'campana', 'campos', 'canavarro', 'canedo', 'canetti',
  'canto', 'capistrano', 'capucho', 'cardoso', 'carli', 'carlos', 'carneiro', 'carraro', 'carrilho', 'carvalho',
  'casagrande', 'casals', 'casas', 'cassiano', 'castelo', 'castilho', 'castro', 'catunda', 'cavalcante', 'cavalcanti',
  'ceara', 'cecilio', 'cerqueira', 'cervantes', 'cesar', 'cescon', 'chagas', 'chaim', 'chammas', 'chaves',
  'chiari', 'cianci', 'cicero', 'cipriano', 'claro', 'claudio', 'clemente', 'coelho', 'coimbra', 'colaco',
  'colombo', 'comin', 'conde', 'conrado', 'constantino', 'conti', 'cordeiro', 'coronel', 'correa', 'correia',
  'cortes', 'cortez', 'costa', 'cotrim', 'coutinho', 'couto', 'covas', 'crespo', 'crivelari', 'cruz',
  'cunha', 'curado', 'curi', 'custodio', 'dallari', 'damasceno', 'dantas', 'danziger', 'daros', 'dasilva',
  'davi', 'davila', 'deandrade', 'deazevedo', 'decastro', 'delamare', 'delfino', 'delgado', 'delima', 'demarchi',
  'demelo', 'denardi', 'denascimento', 'deoliveira', 'depaula', 'depieri', 'derosa', 'desouza', 'dias', 'diego',
  'diniz', 'diogo', 'dionizio', 'domingues', 'donato', 'dornelles', 'drumond', 'duarte', 'duque', 'duraes',
  'dutra', 'eirado', 'elias', 'emilio', 'epitacio', 'escobar', 'esmeraldo', 'espindola', 'esposito', 'esteves',
  'estrada', 'eugenio', 'eustaquio', 'evangelista', 'fabbri', 'fabiano', 'fagundes', 'falcão', 'falcone', 'faria',
  'farias', 'farina', 'faro', 'faustino', 'favaro', 'fayad', 'federmann', 'feijo', 'feitosa', 'felicio',
  'felix', 'fernandes', 'fernandez', 'ferrari', 'ferrao', 'ferraz', 'ferreira', 'ferreiras', 'ferretti', 'ferro',
  'fialho', 'figueira', 'figueiredo', 'figueiroa', 'filippi', 'fioravante', 'fiori', 'fischer', 'fogaça', 'fonseca',
  'fontana', 'fontes', 'fontoura', 'fortes', 'fragoso', 'franca', 'franceschi', 'franco', 'franklin', 'freire',
  'freitas', 'frota', 'frutuoso', 'fujita', 'furtado', 'gabriel', 'gaeta', 'gagliardi', 'galante', 'galindo',
  'gallinari', 'gallo', 'galvao', 'gama', 'garcez', 'garcia', 'garofalo', 'gaspar', 'gatto', 'gaudencio',
  'gentil', 'gentile', 'geraldo', 'germano', 'giacomini', 'gil', 'giordano', 'giovannini', 'girardi', 'giusti',
  'godoy', 'gois', 'gomes', 'goncalves', 'gonzaga', 'gonzalez', 'goulart', 'gouvea', 'gouveia', 'gramacho',
  'grangeiro', 'grassi', 'grasso', 'greco', 'gregorio', 'grimaldi', 'guarda', 'guedes', 'guerra', 'guilherme',
  'guimaraes', 'gusmao', 'gutierrez', 'haddad', 'hahn', 'hara', 'harada', 'hartmann', 'hayashi', 'helena',
  'heliodoro', 'henrique', 'henriques', 'herculano', 'hernandez', 'herrera', 'hidalgo', 'higuchi', 'hipolito', 'hirata',
  'hoffmann', 'holanda', 'homem', 'honorato', 'horta', 'humberto', 'ibiapina', 'idris', 'iglesias', 'inacio',
  'inoue', 'ippolito', 'isidoro', 'ismail', 'italo', 'ito', 'iwasaki', 'izidoro', 'jaber', 'jacinto',
  'jacob', 'jacobina', 'jaime', 'jales', 'januario', 'jaques', 'jardim', 'jesus', 'jimenez', 'joaquim',
  'jordao', 'jorge', 'jose', 'joviano', 'juliao', 'junqueira', 'jurema', 'justino', 'kanashiro', 'kaneko',
  'kato', 'kawakami', 'kawasaki', 'keller', 'khoury', 'kikuchi', 'kimura', 'klein', 'kobayashi', 'koch',
  'koga', 'kojima', 'kondo', 'koyama', 'kramer', 'krause', 'kreisler', 'kudo', 'kuhn', 'kurata',
  'labatut', 'lacerda', 'lages', 'lago', 'laguna', 'lamarca', 'lamego', 'landim', 'lange', 'laranjeira',
  'laredo', 'larissa', 'laura', 'lavoier', 'lazaro', 'leal', 'leao', 'ledesma', 'leite', 'lemos',
  'leonardi', 'leonardo', 'leoncio', 'leone', 'leopoldino', 'lessa', 'liberato', 'lima', 'limongi', 'linares',
  'linhares', 'lins', 'lira', 'lisboa', 'lobato', 'lobo', 'loiola', 'lombardi', 'longo', 'lopes',
  'loreto', 'lorenz', 'lorenzo', 'loureiro', 'lourenço', 'lousada', 'loyola', 'lucas', 'lucena', 'luciano',
  'luis', 'luiz', 'luna', 'luz', 'lyra', 'mabilia', 'macedo', 'machado', 'maciel', 'madruga', 'maffei',
  'magalhaes', 'maggi', 'magno', 'maia', 'mainardi', 'maiorano', 'malafaia', 'malta', 'mancini', 'mandarino',
  'mangabeira', 'manhães', 'manso', 'mansur', 'mantovani', 'maranhao', 'marcelino', 'marchetti', 'marcondes', 'marcos',
  'mariani', 'marinho', 'marini', 'marins', 'marques', 'marquez', 'martinelli', 'martins', 'mascarenhas', 'massa',
  'masson', 'matarazzo', 'mateus', 'matias', 'matos', 'mattos', 'mauricio', 'maximo', 'maia', 'medeiros',
  'medina', 'meira', 'meireles', 'meirelles', 'mello', 'melo', 'mendes', 'mendonca', 'meneses', 'menezes',
  'mercante', 'merlo', 'mesquita', 'messias', 'meyer', 'miguel', 'milani', 'milhomens', 'militão', 'miranda',
  'modesto', 'molinari', 'monaco', 'moniz', 'montagner', 'montenegro', 'monteiro', 'monti', 'mora', 'moraes',
  'morais', 'morales', 'moreira', 'morelli', 'moreno', 'moretti', 'moro', 'mota', 'motta', 'moura',
  'moussa', 'muller', 'munhoz', 'muniz', 'murakami', 'mussolini', 'nadal', 'nagai', 'nagao', 'najjar',
  'nakagawa', 'nakamura', 'nakano', 'nakasato', 'nakashima', 'nammour', 'narciso', 'nascimento', 'nassar', 'navarro',
  'negrao', 'neiva', 'neri', 'neto', 'netto', 'neves', 'nicola', 'nicolau', 'nieto', 'nishi',
  'nishimura', 'nobre', 'nobrega', 'nogueira', 'nolasco', 'noronha', 'novais', 'novaess', 'novelli', 'nunes',
  'offredi', 'ogawa', 'ohara', 'ohta', 'okada', 'okamoto', 'okawa', 'olaio', 'oliva', 'oliveira',
  'onofre', 'ono', 'ornellas', 'ortega', 'ortiz', 'osorio', 'otani', 'otavio', 'otoni', 'ozaki',
  'pacheco', 'pacifico', 'padilha', 'padua', 'paes', 'paim', 'paiva', 'paixao', 'palermo', 'palma',
  'palumbo', 'pantoja', 'paoli', 'papa', 'paranhos', 'parente', 'parra', 'parreiras', 'paschoal', 'pascoal',
  'passos', 'pastor', 'patricio', 'patti', 'paula', 'paulino', 'paulo', 'pavani', 'paz', 'pecanha',
  'peçanha', 'pechincha', 'pedreira', 'pedroso', 'pedrosa', 'peixoto', 'pellegrini', 'penido', 'penna', 'penteado',
  'peralta', 'perazzo', 'perdigao', 'pereira', 'perez', 'peron', 'pessoa', 'petroni', 'piazza', 'picanco',
  'picheth', 'pilar', 'pimenta', 'pimentel', 'pina', 'pinder', 'pinheiro', 'pinto', 'piovesan', 'piragibe',
  'pires', 'pitanga', 'piza', 'pizzatto', 'poças', 'poli', 'polvora', 'pompeu', 'ponte', 'pontes',
  'portela', 'porto', 'portugal', 'povoas', 'praciano', 'prado', 'prates', 'prieto', 'puga', 'quadros',
  'quaresma', 'queiroga', 'queiroz', 'quintal', 'quintanilha', 'quintela', 'quintero', 'rabello', 'rafael', 'rahal',
  'ramalho', 'ramires', 'ramirez', 'ramos', 'rangel', 'ranieri', 'raposo', 'rebelo', 'reboucas', 'rego',
  'regis', 'regueira', 'reinaldo', 'reis', 'remedio', 'renault', 'resende', 'ressurreicao', 'rezende', 'ribas',
  'ribeiro', 'ricardo', 'ricci', 'rinaldi', 'rios', 'rivas', 'rizk', 'rizzi', 'rizzo', 'robalinho',
  'robledo', 'rocha', 'rodrigues', 'rodriguez', 'rollemberg', 'romano', 'romero', 'roquete', 'rosa', 'rosas',
  'rossi', 'rossini', 'roure', 'rubio', 'ruiz', 'sa', 'saad', 'sabino', 'sacramento', 'salazar',
  'salem', 'salgado', 'salomao', 'salvador', 'salviano', 'sampaio', 'samuel', 'sanches', 'sanchez', 'sangalo',
  'sansone', 'santana', 'santoro', 'santos', 'sapucaia', 'saraiva', 'saravia', 'sardenberg', 'sarkis', 'sarmento',
  'sarney', 'sasaki', 'sato', 'scalla', 'schimidt', 'schmidt', 'schneider', 'schultz', 'schwarz', 'seixas',
  'senna', 'serafim', 'serpa', 'serra', 'serrano', 'servulo', 'severo', 'shimada', 'shimizu', 'silva',
  'silveira', 'simas', 'simoes', 'siola', 'siqueira', 'siriani', 'sleiman', 'soares', 'sobreira', 'sobrito',
  'sodre', 'sola', 'soler', 'soncini', 'soriano', 'sorrento', 'soto', 'sousa', 'souza', 'spinelli',
  'stefano', 'stein', 'suarez', 'suzano', 'suzuki', 'taborda', 'tabosa', 'tagliaferro', 'tahan', 'takahashi',
  'talento', 'tamura', 'tanaka', 'tancredo', 'tannous', 'tavares', 'tavora', 'teixeira', 'teles', 'telmo',
  'temer', 'tenorio', 'terceiro', 'thome', 'tiburcio', 'tito', 'tobias', 'toledo', 'tolentino', 'tolosa',
  'tonelli', 'torquato', 'torres', 'tourinho', 'travassos', 'trentini', 'trigueiro', 'trindade', 'turco', 'uchoa',
  'ulhoa', 'urbano', 'urquiza', 'vaca', 'valadao', 'valadão', 'valenca', 'valença', 'valente', 'valentini',
  'valim', 'valois', 'valverde', 'varela', 'vargas', 'vasconcelos', 'vasques', 'vaz', 'veiga', 'veloso',
  'vellozo', 'venancio', 'ventura', 'veras', 'verga', 'vergueiro', 'vespasiano', 'viana', 'vianna', 'vidal',
  'viegas', 'vieira', 'vilaca', 'vilas', 'vilasboas', 'villeneuve', 'villas', 'villela', 'vinhadel', 'virgulino',
  'vital', 'vitoria', 'vivan', 'vogel', 'wagner', 'watanabe', 'weber', 'werner', 'wolf', 'xavier',
  'yamada', 'yamaguchi', 'yamamoto', 'yoshida', 'yunes', 'zago', 'zamboni', 'zanella', 'zanini', 'zanzini',
  'zattar', 'zeferino', 'zenha', 'zerbini', 'zonta',
  // Origem Francesa
  'dubois', 'lefevre', 'roux', 'fontaine', 'chevalier', 'benoit', 'nicolas', 'morin', 'girard', 'bonnet',
  'muller', 'lambert', 'faure', 'andre', 'mercier', 'blanc', 'guerin', 'boyer', 'garnier', 'francois',
  'legrand', 'gauthier', 'garcia', 'perrin', 'robin', 'clement', 'henry', 'roussel', 'mathieu', 'gautier',
  'masson', 'marchand', 'duval', 'denis', 'dumont', 'marie', 'lemaire', 'noel', 'meyer', 'dufour',
  'meunier', 'brun', 'blanchard', 'giraud', 'joly', 'riviere', 'lucas', 'brunet', 'gaillard', 'barbier',
  'arnaud', 'martinez', 'hubert', 'diallo', 'guerrier', 'sauveur', 'bourgeois', 'guillaume', 'moulin', 'adam',
  'picart', 'colin', 'boucher', 'fleury', 'aubert', 'lacroix', 'etienne', 'dupui', 'deschamps', 'huet',
  'barbe', 'marchal', 'millet', 'collet', 'musset', 'pajot', 'renard', 'prevost', 'herve', 'royer',
  'klein', 'mallet', 'weber', 'leger', 'perrot', 'daniel', 'grondin', 'roger', 'hunter', 'cross',
  // Origem Polonesa/Ucraniana
  'nowak', 'kowalski', 'wisniewski', 'wojcik', 'kowalczyk', 'kaminski', 'lewandowski', 'zielinski', 'szymanski', 'wozniak',
  'kozlowski', 'jankowski', 'mazur', 'wojciechowski', 'kwiatkowski', 'krawczyk', 'kaczmarek', 'piotrowski', 'grabowski', 'pawlowski',
  'michalski', 'zajac', 'krol', 'wieczorek', 'jablonski', 'wrobel', 'adamczyk', 'dudek', 'nowicki', 'majewski',
  'olszewski', 'stepien', 'jaworski', 'malik', 'witkowski', 'walczak', 'sikora', 'baran', 'rutkowski', 'michalak',
  'szewczyk', 'ostrowski', 'tomaszewski', 'pietrzak', 'duda', 'zalewski', 'wroblewski', 'marciniak', 'jakobczyk', 'zawadzki',
  'sawicki', 'kaczmarczyk', 'borkowski', 'stefaniak', 'jasinski', 'blaszczyk', 'kaczor', 'szczepanski', 'mroz', 'kucharski',
  'makowski', 'kalinowski', 'lis', 'mazurek', 'wysocki', 'adamski', 'kazmierczak', 'wasilewski', 'sobczak', 'stasiak',
  // Origem Holandesa
  'van dijk', 'de jong', 'bakker', 'de vries', 'van den berg', 'van de ven', 'van der meer', 'van der linden', 'van der wal', 'van der zee',
  'van der heide', 'van der veen', 'van der meulen', 'van der ploeg', 'van der horst', 'van der molen', 'van der heijden', 'van der velde', 'van der woude', 'van der laan',
  'van der spek', 'van der graaf', 'van der steen', 'van der bijl', 'van der sluis', 'van der brink', 'van der vliet', 'van der kamp', 'van der bosch', 'van der kroon',
  'schouten', 'visser', 'post', 'meijer', 'janssen', 'de boer', 'hofman', 'bos', 'vos', 'dekker',
  // Origem Russa/Leste Europeu
  'ivanov', 'smirnov', 'kuznetsov', 'popov', 'vasilyev', 'petrov', 'sokolov', 'mikhailov', 'novikov', 'fedorov',
  'morozov', 'volkov', 'alekseev', 'lebedev', 'semyonov', 'egorov', 'pavlov', 'kozlov', 'stepanov', 'nikolaev',
  'orlov', 'andreev', 'makarov', 'nikitin', 'zakharov', 'zaitsev', 'solovyov', 'borisov', 'yakovlev', 'grigoryev',
  'romanov', 'vorobyov', 'sergeev', 'kuzmin', 'frolov', 'aleksandrov', 'dmitriev', 'korolyov', 'ponomaryov', 'golubev',
  'vinogradov', 'bogdanov', 'voronin', 'matveev', 'belov', 'zhukov', 'titov', 'antonov', 'danilov', 'polyakov',
  // Origem Inglesa/Americana
  'smith', 'johnson', 'williams', 'brown', 'jones', 'miller', 'davis', 'wilson', 'anderson', 'taylor',
  'thomas', 'moore', 'jackson', 'martin', 'lee', 'perez', 'thompson', 'white', 'harris', 'sanchez',
  'clark', 'ramirez', 'lewis', 'robinson', 'walker', 'young', 'allen', 'king', 'wright', 'scott',
  'torres', 'nguyen', 'hill', 'flores', 'green', 'adams', 'nelson', 'baker', 'hall', 'rivera',
  'campbell', 'mitchell', 'carter', 'roberts', 'gomez', 'phillips', 'evans', 'turner', 'diaz', 'parker',
  'cruz', 'edwards', 'collins', 'reyes', 'stewart', 'morris', 'morales', 'murphy', 'cook', 'rogers',
  'gutierrez', 'ortiz', 'morgan', 'cooper', 'peterson', 'bailey', 'reed', 'kelly', 'howard', 'ramos',
  'kim', 'cox', 'ward', 'richardson', 'watson', 'brooks', 'chavez', 'wood', 'james', 'bennett',
  'gray', 'mendoza', 'ruiz', 'hughes', 'price', 'alvarez', 'castillo', 'sanders', 'patel', 'myers',
  'long', 'ross', 'foster', 'jimenez', 'powell', 'jenkins', 'perry', 'russell', 'sullivan', 'bell',
  'coleman', 'butler', 'henderson', 'barnes', 'gonzales', 'fisher', 'vasquez', 'simmons', 'romero', 'jordan',
  'patterson', 'alexander', 'hamilton', 'graham', 'reynolds', 'griffin', 'wallace', 'moreno', 'west', 'cole',
  'hayes', 'bryant', 'herrera', 'gibson', 'ellis', 'tran', 'medina', 'aguilar', 'stevens', 'murray',
  'ford', 'castro', 'marshall', 'owens', 'harrison', 'fernandez', 'mcdonald', 'cruz', 'blanchard', 'rhodes',
  // Origem Escandinava
  'nielsen', 'jensen', 'hansen', 'pedersen', 'andersen', 'christensen', 'larsen', 'sørensen', 'rasmussen', 'jørgensen',
  'petersen', 'madsen', 'kristensen', 'olsen', 'thomsen', 'christiansen', 'poulsen', 'johansen', 'knudsen', 'mortensen',
  'svendsen', 'jacobsen', 'iversen', 'mikkelsen', 'nilsen', 'bakke', 'berg', 'lunde', 'moen', 'nygaard',
  // Mais Italianos
  'abate', 'accardi', 'adamo', 'adriani', 'agosti', 'aiello', 'alberti', 'albini', 'alessi', 'alfano',
  'amadei', 'amatore', 'ambrogio', 'amici', 'andreoletti', 'angelini', 'anselmi', 'antonelli', 'anzalone', 'aprile',
  'arcangeli', 'arena', 'arienti', 'armanni', 'artuso', 'ascoli', 'astolfi', 'attanasio', 'augusto', 'avanzini',
  'babini', 'bacci', 'badalamenti', 'baggio', 'balbi', 'baldan', 'baldi', 'balducci', 'ballerini', 'balzano',
  'bandini', 'baraldi', 'barbagallo', 'barbaro', 'barberis', 'barbi', 'barone', 'barozzi', 'barretta', 'bartoli',
  'basile', 'bassani', 'bassi', 'battaglia', 'battistini', 'bellandi', 'bellante', 'bellavia', 'belli', 'bellini',
  'bellomo', 'bellotti', 'belotti', 'beltrami', 'benatti', 'benedetti', 'benini', 'benvenuti', 'berardi', 'beretta',
  'bergamini', 'bergamo', 'berlusconi', 'bernardi', 'bernardini', 'bernasconi', 'bertani', 'berti', 'bertini', 'bertoli',
  'bertolini', 'bertolotto', 'bertone', 'bertotto', 'besana', 'betta', 'betti', 'bettini', 'bevilacqua', 'biagi',
  'biagini', 'biancardi', 'bianchini', 'bianco', 'biasi', 'biasini', 'biffi', 'bigi', 'bini', 'biondi',
  'bisio', 'bizzarri', 'boano', 'boccardi', 'boccia', 'boffa', 'bogani', 'boito', 'bolis', 'bolla',
  'bologna', 'bolognesi', 'bombardieri', 'bonaccorsi', 'bonanno', 'bonardi', 'bonato', 'bonelli', 'bonfanti', 'bonfiglio',
  'bongiovi', 'bonini', 'bono', 'bonvicini', 'borghi', 'borgo', 'borrelli', 'borsellino', 'borsi', 'bortolotti',
  'boscariol', 'boschi', 'bosco', 'boscolo', 'boselli', 'bosi', 'bosio', 'bossa', 'bottari', 'bottinelli',
  'bovone', 'bozza', 'bracco', 'bragagnolo', 'brambilla', 'branca', 'brancato', 'brandi', 'braschi', 'bravi',
  'brembilla', 'brescia', 'bressan', 'briasco', 'brizzi', 'brogi', 'brunelli', 'brunetti', 'bruni', 'bruschi',
  'bucci', 'bufalini', 'bugatti', 'bulgarelli', 'buonarroti', 'buonocore', 'buratti', 'busacca', 'buscaglia', 'buscemi',
  'busi', 'busnelli', 'buso', 'bussola', 'butti', 'buzzati', 'buzzo', 'cabrini', 'caccamo', 'cacciatore',
  // Mais Alemães
  'abendroth', 'acker', 'adelmann', 'adler', 'ahrendt', 'ahrens', 'albrecht', 'altmann', 'amann', 'amrhein',
  'andres', 'appel', 'arendt', 'arndt', 'arnold', 'asmus', 'aue', 'auer', 'augustin', 'axmann',
  'baader', 'baas', 'babick', 'bach', 'bachmann', 'backhaus', 'bader', 'baehr', 'baer', 'baier',
  'baldes', 'balduin', 'ballack', 'baltes', 'baltz', 'balz', 'bamberg', 'bandelow', 'bangert', 'bannert',
  'baron', 'bartel', 'bartels', 'barth', 'barthel', 'bartsch', 'basler', 'bastian', 'batz', 'baudisch',
  'bauer', 'bauernfeind', 'baumann', 'baumbach', 'baumeister', 'baumgart', 'baumgarten', 'baumgartner', 'baur', 'baus',
  'bausch', 'bayer', 'becher', 'becht', 'bechtel', 'beck', 'becke', 'becker', 'beckert', 'beckmann',
  'beer', 'beermann', 'beetz', 'behm', 'behn', 'behnke', 'behr', 'behrend', 'behrendt', 'behrens',
  'beier', 'beil', 'beissel', 'beitz', 'belz', 'bender', 'bendig', 'benedikt', 'beneke', 'benner',
  'benning', 'bensch', 'bentz', 'benz', 'berberich', 'berchtold', 'berg', 'bergemann', 'bergen', 'berger',
  'bergmann', 'berk', 'berndt', 'berner', 'bernhard', 'bernhardt', 'berning', 'berthold', 'bertram', 'berz',
  'bescherer', 'besser', 'bethge', 'bethke', 'beutel', 'beutler', 'bey', 'beyer', 'beyersdorf', 'beyschlag',
  'bezold', 'bibel', 'bichler', 'bieber', 'biehl', 'bielefeld', 'bieler', 'bier', 'biermann', 'biester',
  'bietz', 'biller', 'binder', 'bing', 'birkenstock', 'birkner', 'birnbaum', 'bischof', 'bischoff', 'bissinger',
  'bitter', 'bittner', 'blank', 'blanke', 'blankenburg', 'blatter', 'blau', 'blechschmidt', 'blei', 'bless',
  'blessin', 'bleuler', 'bley', 'block', 'blohm', 'bluhm', 'blum', 'blumberg', 'blume', 'blumenberg',
  // Mais Espanhóis
  'abad', 'abalo', 'abascal', 'abeledo', 'abellán', 'abril', 'acevedo', 'acosta', 'acuña', 'adán',
  'aguado', 'agudo', 'aguilar', 'aguilera', 'aguirre', 'agustí', 'ahumada', 'aitana', 'alameda', 'alamo',
  'alarcón', 'alba', 'albaladejo', 'albarracín', 'alberdi', 'albero', 'albert', 'alberto', 'albiol', 'albornoz',
  'albuquerque', 'alcalá', 'alcalde', 'alcántara', 'alcaraz', 'alcázar', 'alcocer', 'alcón', 'alcorta', 'alcudia',
  'alday', 'alegre', 'alegría', 'alejandro', 'alemán', 'alemany', 'alfaro', 'alfonso', 'algaba', 'alguacil',
  'aliaga', 'alicante', 'almagro', 'almansa', 'almazán', 'almeida', 'almería', 'almodóvar', 'alonso', 'alsina',
  'altamira', 'altamirano', 'alvarado', 'álvarez', 'alvaro', 'alvear', 'amado', 'amador', 'amaro', 'amaya',
  'amigo', 'amor', 'amorós', 'ampudia', 'anaya', 'andrada', 'andrade', 'andrés', 'andreu', 'ángel',
  'anglada', 'anguita', 'angulo', 'ansorena', 'antequera', 'antón', 'antúnez', 'aparicio', 'aragonés', 'aranda',
  'arango', 'aranza', 'aranzabal', 'araque', 'araujo', 'araya', 'arboleda', 'arce', 'archilla', 'arcos',
  'arellano', 'arenas', 'arévalo', 'argüelles', 'arias', 'ariza', 'arjona', 'armas', 'armendáriz', 'arnau',
  'aroca', 'arona', 'aróstegui', 'arredondo', 'arriaga', 'arribas', 'arrieta', 'arroyo', 'arteaga', 'artigas',
  'asensio', 'asís', 'astorga', 'asturias', 'asua', 'atienza', 'augusto', 'avalos', 'avendaño', 'ávila',
  'avilés', 'ayala', 'ayllón', 'ayuso', 'azaña', 'azcona', 'aznar', 'azofra', 'azorin', 'azpeitia',
  'badía', 'baena', 'baez', 'bagur', 'bahamonde', 'balaguer', 'balboa', 'balderas', 'baldomero', 'ballester',
  'ballesteros', 'balmaseda', 'balsera', 'bañon', 'baños', 'baquero', 'barahona', 'barba', 'barbado', 'barbara',
  'barberá', 'barbero', 'barca', 'barceló', 'bárcena', 'barco', 'bardem', 'barella', 'barquero', 'barranco',
  'barreda', 'barreiro', 'barrera', 'barriga', 'barrio', 'barrionuevo', 'barrios', 'barroso', 'bartolomé', 'bas',
  // Mais Japoneses
  'akagi', 'akamine', 'akimoto', 'akiyama', 'amano', 'anraku', 'aoyama', 'arakaki', 'arakawa', 'araki',
  'arima', 'arita', 'asada', 'asai', 'asano', 'asato', 'ashikaga', 'asou', 'azuma', 'baba',
  'chiba', 'date', 'deguchi', 'doi', 'ebara', 'ebina', 'eguchi', 'enomoto', 'eto', 'ezaki',
  'fuchigami', 'fujikawa', 'fujimaki', 'fujimura', 'fujino', 'fujisawa', 'fujishiro', 'fujita', 'fujiwara', 'fukuda',
  'fukuhara', 'fukui', 'fukumoto', 'fukunaga', 'fukushima', 'fukuyama', 'funai', 'furukawa', 'furusawa', 'furuta',
  'furuya', 'fuse', 'goya', 'hada', 'hagiwara', 'hamada', 'hamaguchi', 'hamamoto', 'hamano', 'hamasaki',
  'hanada', 'hanaoka', 'handa', 'hano', 'hanzawa', 'hara', 'harada', 'haraguchi', 'harasawa', 'haruta',
  'hase', 'hasebe', 'hasegawa', 'hashiguchi', 'hashimoto', 'hashizume', 'hasumi', 'hata', 'hatakeyama', 'hatanaka',
  'hatano', 'hatoyama', 'hattori', 'hayakawa', 'hayami', 'hayasaka', 'hayashi', 'hayashida', 'hiano', 'hida',
  'hidaka', 'higashi', 'higashide', 'higuchi', 'hino', 'hirai', 'hirakawa', 'hiraki', 'hiramatsu', 'hirano',
  'hiraoka', 'hirasawa', 'hirata', 'hirayama', 'hirose', 'hirota', 'hishida', 'hishinuma', 'honda', 'honma',
  'hori', 'horie', 'horiguchi', 'horii', 'horikawa', 'horikoshi', 'horimoto', 'horita', 'horiuchi', 'hoshi',
  'hoshino', 'hosoda', 'hosokawa', 'hosono', 'hosoya', 'hotta', 'hyodo', 'ichikawa', 'ichimura', 'ichino',
  // Mais Portugueses/Brasileiros
  'abel', 'abrahao', 'abrantes', 'abreu', 'abuquerque', 'accioly', 'acunha', 'adao', 'adauto', 'adelino',
  'adriano', 'afonso', 'agostinho', 'aguiar', 'aires', 'albuquerque', 'alcantara', 'alencar', 'alexandre', 'alfredo',
  'almeida', 'alvarenga', 'alvaro', 'alves', 'alvim', 'amado', 'amancio', 'amaral', 'amarante', 'amarilio',
  'amaro', 'amauri', 'amaury', 'ambrosio', 'americo', 'amorim', 'anchieta', 'andrade', 'andrades', 'andre',
  'andres', 'andressa', 'angela', 'angelica', 'angelo', 'anjos', 'anselmo', 'antao', 'antes', 'antero',
  'antonia', 'antonio', 'antunes', 'aparicio', 'apolonio', 'aquino', 'aragao', 'arantes', 'arao', 'araujo',
  'arcanjo', 'ari', 'ariel', 'arimateia', 'arinos', 'aristeu', 'aristides', 'armando', 'arnaldo', 'arnon',
  'arrais', 'arruda', 'artur', 'asfora', 'assis', 'assuncao', 'atala', 'ataliba', 'atila', 'augusta',
  'augusto', 'aurea', 'aurelio', 'avelar', 'avelino', 'avila', 'azevedo', 'bacelar', 'baeta', 'baggio',
  'bahia', 'balduino', 'baltazar', 'bandeira', 'baptista', 'barata', 'barbosa', 'barcelos', 'barreto', 'barreto',
  'barros', 'barroso', 'basilio', 'bastos', 'batista', 'beatriz', 'beira', 'beiramar', 'belchior', 'belfort',
  'belo', 'beltrao', 'benedito', 'benicio', 'benites', 'benito', 'benjamin', 'bento', 'berenguer', 'bermudes',
  'bernardes', 'bernardino', 'bernardo', 'berthe', 'bertoldo', 'bezerra', 'bicalho', 'bidu', 'bispo', 'bittencourt',
  'boas', 'boaventura', 'bocaiuva', 'bonfim', 'borba', 'borges', 'botelho', 'braga', 'braganca', 'brandao',
  'brasil', 'brasileiro', 'brito', 'brizola', 'buarque', 'bueno', 'bulhoes', 'burlamaqui', 'cabral', 'caetano',
  'caires', 'cajado', 'calado', 'calazans', 'caldas', 'caldeira', 'calheiros', 'calmon', 'camacho', 'camara',
  'camargo', 'camelo', 'caminha', 'campana', 'campos', 'canavarro', 'canedo', 'canetti', 'canto', 'capistrano',
  'capucho', 'cardoso', 'carli', 'carlos', 'carmo', 'carneiro', 'carraro', 'carrilho', 'carvalho', 'casagrande',
  'casals', 'casas', 'cassiano', 'castelo', 'castilho', 'castro', 'catunda', 'cavalcante', 'cavalcanti', 'ceara',
  'cecilio', 'cerqueira', 'cesar', 'cescon', 'chagas', 'chaim', 'chammas', 'chaves', 'chiari', 'cianci',
  'cicero', 'cipriano', 'claro', 'claudio', 'clemente', 'coelho', 'coimbra', 'colaco', 'colombo', 'comin',
  'conde', 'conrado', 'constantino', 'conti', 'cordeiro', 'coronel', 'correa', 'correia', 'cortes', 'cortez',
  'costa', 'cotrim', 'coutinho', 'couto', 'covas', 'crespo', 'crivelari', 'cruz', 'cunha', 'curado',
  'curi', 'custodio', 'dallari', 'damasceno', 'dantas', 'danziger', 'daros', 'dasilva', 'davi', 'davila',
  'deandrade', 'deazevedo', 'decastro', 'delamare', 'delfino', 'delgado', 'delima', 'demarchi', 'demelo', 'denardi',
  'denascimento', 'deoliveira', 'depaula', 'depieri', 'derosa', 'desouza', 'dias', 'diego', 'diniz', 'diogo',
  'dionizio', 'domingues', 'donato', 'dornelles', 'drumond', 'duarte', 'duque', 'duraes', 'dutra', 'eirado',
  'elias', 'emilio', 'epitacio', 'escobar', 'esmeraldo', 'espindola', 'esposito', 'esteves', 'estrada', 'eugenio',
  'eustaquio', 'evangelista', 'fabbri', 'fabiano', 'fagundes', 'falcão', 'falcone', 'faria', 'farias', 'farina',
  'faro', 'faustino', 'favaro', 'fayad', 'federmann', 'feijo', 'feitosa', 'felicio', 'felix', 'fernandes',
  'fernandez', 'ferrari', 'ferrao', 'ferraz', 'ferreira', 'ferreiras', 'ferretti', 'ferro', 'fialho', 'figueira',
  'figueiredo', 'figueiroa', 'filippi', 'fioravante', 'fiori', 'fischer', 'fogaça', 'fonseca', 'fontana', 'fontes',
  'fontoura', 'fortes', 'fragoso', 'franca', 'franceschi', 'franco', 'franklin', 'freire', 'freitas', 'frota',
  'frutuoso', 'fujita', 'furtado', 'gabriel', 'gaeta', 'gagliardi', 'galante', 'galindo', 'gallinari', 'gallo',
  'galvao', 'gama', 'garcez', 'garcia', 'garofalo', 'gaspar', 'gatto', 'gaudencio', 'gentil', 'gentile',
  'geraldo', 'germano', 'giacomini', 'gil', 'giordano', 'giovannini', 'girardi', 'giusti', 'godoy', 'gois',
  'gomes', 'goncalves', 'gonzaga', 'gonzalez', 'goulart', 'gouvea', 'gouveia', 'gramacho', 'grangeiro', 'grassi',
  'grasso', 'greco', 'gregorio', 'grimaldi', 'guarda', 'guedes', 'guerra', 'guilherme', 'guimaraes', 'gusmao',
  'gutierrez', 'haddad', 'hahn', 'hara', 'harada', 'hartmann', 'hayashi', 'helena', 'heliodoro', 'henrique',
  'henriques', 'herculano', 'hernandez', 'herrera', 'hidalgo', 'higuchi', 'hipolito', 'hirata', 'hoffmann', 'holanda',
  'homem', 'honorato', 'horta', 'humberto', 'ibiapina', 'idris', 'iglesias', 'inacio', 'inoue', 'ippolito',
  'isidoro', 'ismail', 'italo', 'ito', 'iwasaki', 'izidoro', 'jaber', 'jacinto', 'jacob', 'jacobina',
  'jaime', 'jales', 'januario', 'jaques', 'jardim', 'jesus', 'jimenez', 'joaquim', 'jordao', 'jorge',
  'jose', 'joviano', 'juliao', 'junqueira', 'jurema', 'justino', 'kanashiro', 'kaneko', 'kato', 'kawakami',
  'kawasaki', 'keller', 'khoury', 'kikuchi', 'kimura', 'klein', 'kobayashi', 'koch', 'koga', 'kojima',
  'kondo', 'koyama', 'kramer', 'krause', 'kreisler', 'kudo', 'kuhn', 'kurata', 'labatut', 'lacerda',
  'lages', 'lago', 'laguna', 'lamarca', 'lamego', 'landim', 'lange', 'laranjeira', 'laredo', 'larissa',
  'laura', 'lavoier', 'lazaro', 'leal', 'leao', 'ledesma', 'leite', 'lemos', 'leonardi', 'leonardo',
  'leoncio', 'leone', 'leopoldino', 'lessa', 'liberato', 'lima', 'limongi', 'linares', 'linhares', 'lins',
  'lira', 'lisboa', 'lobato', 'lobo', 'loiola', 'lombardi', 'longo', 'lopes', 'loreto', 'lorenz',
  'lorenzo', 'loureiro', 'lourenço', 'lousada', 'loyola', 'lucas', 'lucena', 'luciano', 'luis', 'luiz',
  'luna', 'luz', 'lyra', 'mabilia', 'macedo', 'machado', 'maciel', 'madruga', 'maffei', 'magalhaes',
  'maggi', 'magno', 'maia', 'mainardi', 'maiorano', 'malafaia', 'malta', 'mancini', 'mandarino', 'mangabeira',
  'manhães', 'manso', 'mansur', 'mantovani', 'maranhao', 'marcelino', 'marchetti', 'marcondes', 'marcos', 'mariani',
  'marinho', 'marini', 'marins', 'marques', 'marquez', 'martinelli', 'martins', 'mascarenhas', 'massa', 'masson',
  'matarazzo', 'mateus', 'matias', 'matos', 'mattos', 'mauricio', 'maximo', 'maia', 'medeiros', 'medina',
  'meira', 'meireles', 'meirelles', 'mello', 'melo', 'mendes', 'mendonca', 'meneses', 'menezes', 'mercante',
  'merlo', 'mesquita', 'messias', 'meyer', 'miguel', 'milani', 'milhomens', 'militão', 'miranda', 'modesto',
  'molinari', 'monaco', 'moniz', 'montagner', 'montenegro', 'monteiro', 'monti', 'mora', 'moraes', 'morais',
  'morales', 'moreira', 'morelli', 'moreno', 'moretti', 'moro', 'mota', 'motta', 'moura', 'moussa',
  'muller', 'munhoz', 'muniz', 'murakami', 'mussolini', 'nadal', 'nagai', 'nagao', 'najjar', 'nakagawa',
  'nakamura', 'nakano', 'nakasato', 'nakashima', 'nammour', 'narciso', 'nascimento', 'nassar', 'navarro', 'negrao',
  'neiva', 'neri', 'neto', 'netto', 'neves', 'nicola', 'nicolau', 'nieto', 'nishi', 'nishimura',
  'nobre', 'nobrega', 'nogueira', 'nolasco', 'noronha', 'novais', 'novaess', 'novelli', 'nunes', 'offredi',
  'ogawa', 'ohara', 'ohta', 'okada', 'okamoto', 'okawa', 'olaio', 'oliva', 'oliveira', 'onofre',
  'ono', 'ornellas', 'ortega', 'ortiz', 'osorio', 'otani', 'otavio', 'otoni', 'ozaki', 'pacheco',
  'pacifico', 'padilha', 'padua', 'paes', 'paim', 'paiva', 'paixao', 'palermo', 'palma', 'palumbo',
  'pantoja', 'paoli', 'papa', 'paranhos', 'parente', 'parra', 'parreiras', 'paschoal', 'pascoal', 'passos',
  'pastor', 'patricio', 'patti', 'paula', 'paulino', 'paulo', 'pavani', 'paz', 'pecanha', 'peçanha',
  'pechincha', 'pedreira', 'pedroso', 'pedrosa', 'peixoto', 'pellegrini', 'penido', 'penna', 'penteado', 'peralta',
  'perazzo', 'perdigao', 'pereira', 'perez', 'peron', 'pessoa', 'petroni', 'piazza', 'picanco', 'picheth',
  'pilar', 'pimenta', 'pimentel', 'pina', 'pinder', 'pinheiro', 'pinto', 'piovesan', 'piragibe', 'pires',
  'pitanga', 'piza', 'pizzatto', 'poças', 'poli', 'polvora', 'pompeu', 'ponte', 'pontes', 'portela',
  'porto', 'portugal', 'povoas', 'praciano', 'prado', 'prates', 'prieto', 'puga', 'quadros', 'quaresma',
  'queiroga', 'queiroz', 'quintal', 'quintanilha', 'quintela', 'quintero', 'rabello', 'rafael', 'rahal', 'ramalho',
  'ramires', 'ramirez', 'ramos', 'rangel', 'ranieri', 'raposo', 'rebelo', 'reboucas', 'rego', 'regis',
  'regueira', 'reinaldo', 'reis', 'remedio', 'renault', 'resende', 'ressurreicao', 'rezende', 'ribas', 'ribeiro',
  'ricardo', 'ricci', 'rinaldi', 'rios', 'rivas', 'rizk', 'rizzi', 'rizzo', 'robalinho', 'robledo',
  'rocha', 'rodrigues', 'rodriguez', 'rollemberg', 'romano', 'romero', 'roquete', 'rosa', 'rosas', 'rossi',
  'rossini', 'roure', 'rubio', 'ruiz', 'sa', 'saad', 'sabino', 'sacramento', 'salazar', 'salem',
  'salgado', 'salomao', 'salvador', 'salviano', 'sampaio', 'samuel', 'sanches', 'sanchez', 'sangalo', 'sansone',
  'santana', 'santoro', 'santos', 'sapucaia', 'saraiva', 'saravia', 'sardenberg', 'sarkis', 'sarmento', 'sarney',
  'sasaki', 'sato', 'scalla', 'schimidt', 'schmidt', 'schneider', 'schultz', 'schwarz', 'seixas', 'senna',
  'serafim', 'serpa', 'serra', 'serrano', 'servulo', 'severo', 'shimada', 'shimizu', 'silva', 'silveira',
  'simas', 'simoes', 'siola', 'siqueira', 'siriani', 'sleiman', 'soares', 'sobreira', 'sobrito', 'sodre',
  'sola', 'soler', 'soncini', 'soriano', 'sorrento', 'soto', 'sousa', 'souza', 'spinelli', 'stefano',
  'stein', 'suarez', 'suzano', 'suzuki', 'taborda', 'tabosa', 'tagliaferro', 'tahan', 'takahashi', 'talento',
  'tamura', 'tanaka', 'tancredo', 'tannous', 'tavares', 'tavora', 'teixeira', 'teles', 'telmo', 'temer',
  'tenorio', 'terceiro', 'thome', 'tiburcio', 'tito', 'tobias', 'toledo', 'tolentino', 'tolosa', 'tonelli',
  'torquato', 'torres', 'tourinho', 'travassos', 'trentini', 'trigueiro', 'trindade', 'turco', 'uchoa', 'ulhoa',
  'urbano', 'urquiza', 'vaca', 'valadao', 'valadão', 'valenca', 'valença', 'valente', 'valentini', 'valim',
  'valois', 'valverde', 'varela', 'vargas', 'vasconcelos', 'vasques', 'vaz', 'veiga', 'veloso', 'vellozo',
  'venancio', 'ventura', 'veras', 'verga', 'vergueiro', 'vespasiano', 'viana', 'vianna', 'vidal', 'viegas',
  'vieira', 'vilaca', 'vilas', 'vilasboas', 'villeneuve', 'villas', 'villela', 'vinhadel', 'virgulino', 'vital',
  'vitoria', 'vivan', 'vogel', 'wagner', 'watanabe', 'weber', 'werner', 'wolf', 'xavier', 'yamada',
  'yamaguchi', 'yamamoto', 'yoshida', 'yunes', 'zago', 'zamboni', 'zanella', 'zanini', 'zanzini', 'zattar',
  'zeferino', 'zenha', 'zerbini', 'zonta',
  // Origem Grega
  'papadopoulos', 'georgiou', 'nikolaidis', 'katsaros', 'angelopoulos', 'karagiannis', 'dimitriou', 'vasiliou', 'papageorgiou', 'stefanidis',
  'giannopoulos', 'kontos', 'makris', 'pavlidis', 'ioannidis', 'christodoulou', 'theodorou', 'panagiotopoulos', 'kyriakidis', 'galanis',
  // Origem Turca
  'yilmaz', 'kaya', 'demir', 'sahin', 'celik', 'yildiz', 'arslan', 'dogan', 'erdogan', 'koc',
  'kurt', 'ozdemir', 'aydin', 'ozturk', 'aksoy', 'polat', 'guler', 'keskin', 'bulut', 'can',
  // Origem Indiana
  'singh', 'kumar', 'sharma', 'patel', 'gupta', 'reddy', 'khan', 'verma', 'yadav', 'rao',
  'jain', 'shah', 'mishra', 'joshi', 'nair', 'kulkarni', 'choudhury', 'bhatt', 'iyer', 'pillai',
  // Origem Chinesa
  'wang', 'li', 'zhang', 'liu', 'chen', 'yang', 'huang', 'zhao', 'wu', 'zhou',
  'xu', 'sun', 'ma', 'zhu', 'hu', 'guo', 'he', 'lin', 'gao', 'luo',
  // Origem Coreana
  'kim', 'lee', 'park', 'choi', 'jung', 'kang', 'cho', 'yoon', 'jang', 'shin',
  'han', 'oh', 'seo', 'jeon', 'kwon', 'hwang', 'song', 'ahn', 'lim', 'yoo',
  // Origem Vietnamita
  'nguyen', 'tran', 'le', 'pham', 'huynh', 'hoang', 'phan', 'vu', 'dang', 'bui',
  'do', 'ho', 'ngo', 'duong', 'ly',
  // Origem Sul-Americana (Andina/Hispânica)
  'tapia', 'rojas', 'mamani', 'quispe', 'flores', 'sanchez', 'garcia', 'rodriguez', 'lopez', 'martinez',
  'gonzalez', 'perez', 'ramirez', 'torres', 'diaz', 'vargas', 'castro', 'morales', 'herrera', 'medina',
  // Adicionais diversos para volume final
  'abbott', 'abernathy', 'abraham', 'abrams', 'ackerman', 'adair', 'adamson', 'adkins', 'adler', 'agnew',
  'aiken', 'ainsley', 'aitken', 'akers', 'albert', 'albertson', 'albright', 'alden', 'aldridge', 'alexander',
  'alford', 'allan', 'allard', 'allison', 'allman', 'alston', 'alton', 'alvord', 'ambrose', 'ames',
  'amos', 'amundson', 'amy', 'anderson', 'andresen', 'andrew', 'andrews', 'anthony', 'appleton', 'archer',
  'archibald', 'armstrong', 'arnold', 'arrington', 'arthur', 'ashby', 'ashley', 'ashton', 'atkins', 'atkinson',
  'atwater', 'atwell', 'atwood', 'austin', 'averill', 'avery', 'ayer', 'ayers', 'babbitt', 'babcock',
  'babson', 'bachman', 'bacon', 'badger', 'bagley', 'bailey', 'bain', 'baird', 'baker', 'balch',
  'balcom', 'baldwin', 'ball', 'ballard', 'ballou', 'bancroft', 'bangs', 'banks', 'banning', 'bannister',
  'barber', 'barbour', 'barclay', 'bard', 'bardeen', 'bardwell', 'barker', 'barlow', 'barnard', 'barnes',
  'barney', 'barnum', 'barr', 'barrell', 'barrett', 'barron', 'barrows', 'barry', 'barstow', 'bartholomew',
  'bartlett', 'barton', 'bascom', 'bass', 'bassett', 'batchelder', 'bateman', 'bates', 'battles', 'bauman',
  'baxter', 'bayley', 'beach', 'beal', 'beale', 'beals', 'beaman', 'bean', 'beard', 'beardsley',
  'beattie', 'beatty', 'beauchamp', 'beaumont', 'beckwith', 'beebe', 'beech', 'beecher', 'beers', 'belcher',
  'belden', 'belknap', 'bellamy', 'bellows', 'belt', 'beman', 'bemis', 'benedict', 'benjamin', 'benner',
  'bennett', 'benson', 'bent', 'bentley', 'benton', 'bergen', 'berry', 'bertram', 'besse', 'best',
  'betts', 'beverly', 'beyer', 'bickford', 'biddle', 'bidwell', 'bierce', 'bigelow', 'billings', 'bingham',
  'binney', 'birch', 'bird', 'bishop', 'bissell', 'bixby', 'black', 'blackburn', 'blackman', 'blackwell',
  'blair', 'blaisdell', 'blake', 'blakeslee', 'blanchard', 'bland', 'blatchford', 'blauvelt', 'bliss', 'blodgett',
  'blood', 'bloomfield', 'blossom', 'blount', 'boardman', 'bodwell', 'bogardus', 'bogart', 'boggs', 'bogue',
  'boise', 'bolles', 'bolton', 'bond', 'bonner', 'bonney', 'boone', 'booth', 'borden', 'borland',
  'bostwick', 'bosworth', 'bottomley', 'boughton', 'bourn', 'bourne', 'bouton', 'boutwell', 'bowden', 'bowditch',
  'bowdoin', 'bowen', 'bowers', 'bowie', 'bowker', 'bowles', 'bowman', 'boyce', 'boyd', 'boyden',
  'boyer', 'boyington', 'boyle', 'boynton', 'brackett', 'bradbury', 'bradford', 'bradlee', 'bradley', 'bradshaw',
  'bradt', 'brady', 'bragdon', 'bragg', 'brainard', 'brainerd', 'braithwaite', 'braman', 'branch', 'brand',
  'brandon', 'brannan', 'bratton', 'bray', 'brayton', 'breckenridge', 'breed', 'breese', 'bremer', 'brennan',
  'brent', 'brenton', 'brett', 'brewer', 'brewster', 'brice', 'bridge', 'bridges', 'bridgman', 'briggs',
  'brigham', 'bright', 'brinkerhoff', 'brinkley', 'brinton', 'brisbane', 'bristol', 'britton', 'broadhead', 'brock',
  'brockett', 'brockman', 'brockway', 'brokaw', 'bronson', 'brooke', 'brooks', 'broom', 'broughton', 'brower',
  'brownell', 'browning', 'brownlee', 'brownson', 'bruce', 'brush', 'bryan', 'bryant', 'bryce', 'bryson',
  'buchanan', 'buck', 'buckingham', 'buckley', 'buckman', 'bucknam', 'buckner', 'buel', 'buell', 'buffum',
  'bugbee', 'bulkley', 'bull', 'bullard', 'bullock', 'bumpus', 'bunce', 'bunker', 'bunnell', 'burbank',
  'burch', 'burchard', 'burdick', 'burge', 'burgess', 'burke', 'burleigh', 'burley', 'burlingame', 'burnap',
  'burnet', 'burnett', 'burnham', 'burns', 'burr', 'burrall', 'burrell', 'burrill', 'burritt', 'burroughs',
  'burrows', 'burt', 'burton', 'burwell', 'bushnell', 'buss', 'bussey', 'butler', 'butterfield', 'butterworth',
  'button', 'butts', 'buxton', 'byers', 'byington', 'byrd', 'byrne', 'byron', 'cabot', 'cadwalader',
  'cadwell', 'cady', 'cahill', 'cain', 'calder', 'caldwell', 'calef', 'calhoun', 'calkins', 'call',
  'callahan', 'callender', 'calverley', 'calvert', 'cameron', 'camp', 'campbell', 'canfield', 'cann', 'cannon',
  'cantrell', 'capen', 'capron', 'card', 'cardwell', 'carey', 'cargill', 'carhart', 'carleton', 'carlisle',
  'carlson', 'carlton', 'carman', 'carmichael', 'carnahan', 'carnes', 'carney', 'carpenter', 'carr', 'carrington',
  'carroll', 'carruth', 'carson', 'carter', 'cartwright', 'carver', 'cary', 'case', 'casey', 'cass',
  'cassidy', 'castle', 'caswell', 'cathcart', 'catlin', 'cavanaugh', 'caverly', 'cecil', 'chadbourne', 'chadwick',
  'chaffee', 'chalmers', 'chamberlain', 'chamberlin', 'chambers', 'champion', 'champlain', 'champlin', 'chandler', 'chaney',
  'chapin', 'chaplin', 'chapman', 'chappell', 'charles', 'charlton', 'chase', 'chatfield', 'chauncey', 'cheever',
  'cheney', 'cherry', 'chesley', 'chester', 'chestnut', 'chevalier', 'chew', 'chichester', 'child', 'childs',
  'chipman', 'chisholm', 'chittenden', 'choate', 'christian', 'christie', 'christy', 'chubb', 'church', 'churchill',
  'cilley', 'claggett', 'claflin', 'clancy', 'clapp', 'clare', 'clark', 'clarke', 'clarkson', 'clary',
  'clay', 'clayton', 'cleaveland', 'cleaves', 'clemens', 'clement', 'clements', 'cleveland', 'clifford', 'clifton',
  'clinch', 'cline', 'clinton', 'clough', 'clowes', 'clyde', 'coale', 'coan', 'coates', 'cobb',
  'coburn', 'cochran', 'cochrane', 'cockrell', 'coddington', 'codman', 'codwise', 'coe', 'coffin', 'coggeshall',
  'cogswell', 'coit', 'coker', 'colburn', 'colby', 'colcord', 'cole', 'coleman', 'coles', 'colgate',
  'collier', 'collins', 'colman', 'colton', 'colver', 'colvin', 'colwell', 'combs', 'compton', 'comstock',
  'conant', 'condit', 'condon', 'cone', 'conger', 'conklin', 'conkling', 'conley', 'connell', 'connelly',
  'conner', 'conover', 'conrad', 'converse', 'conway', 'cook', 'cooke', 'cooley', 'coolidge', 'coombs',
  'coon', 'cooney', 'cooper', 'cope', 'copeland', 'corbett', 'corbin', 'corcoran', 'cordis', 'corey',
  'corliss', 'cornelius', 'cornell', 'corning', 'cornish', 'cornwall', 'cornwell', 'corwin', 'cory', 'cosgrove',
  'cotter', 'cotton', 'couch', 'coughlin', 'coulter', 'courtney', 'cousins', 'covell', 'coverly', 'cowan',
  'cowell', 'cowen', 'cowles', 'cowperthwaite', 'cox', 'coy', 'coyle', 'crafts', 'craig', 'crain',
  'crandall', 'crane', 'cranston', 'crapo', 'crary', 'crawford', 'creighton', 'crews', 'crittenden', 'crocker',
  'crockett', 'crofoot', 'croft', 'cromwell', 'cronin', 'crook', 'crooks', 'crosby', 'cross', 'crossman',
  'crouch', 'crow', 'crowell', 'crowley', 'crowninshield', 'crozier', 'crump', 'cudworth', 'culbertson', 'cullen',
  'culver', 'cumming', 'cummings', 'cunningham', 'currier', 'curry', 'curtis', 'curtiss', 'cushing', 'cushman',
  'cutler', 'cutter', 'cutting', 'dabney', 'daggett', 'dailey', 'daily', 'dakota', 'dale', 'daley',
  'dalrymple', 'dalton', 'daly', 'dame', 'damon', 'dana', 'dane', 'danforth', 'daniel', 'daniels',
  'darby', 'darling', 'darlington', 'darrow', 'dart', 'davenport', 'davidson', 'davie', 'davies', 'davis',
  'davison', 'dawes', 'dawson', 'day', 'dayton', 'deacon', 'dean', 'deane', 'dearborn', 'deering',
  'deforest', 'dekay', 'delafield', 'delancey', 'deland', 'delano', 'delany', 'dell', 'deming', 'demorest',
  'denison', 'denman', 'dennett', 'denney', 'dennie', 'denning', 'dennis', 'dennison', 'denny', 'denslow',
  'denton', 'depuy', 'derby', 'derrick', 'devereux', 'devine', 'devotion', 'dewey', 'dewing', 'dewitt',
  'dexter', 'dibble', 'dickens', 'dickerman', 'dickerson', 'dickinson', 'dickman', 'dickson', 'dike', 'dill',
  'dillingham', 'dillon', 'diman', 'dimick', 'dimmock', 'dimon', 'dingley', 'dinsmore', 'disbrow', 'ditson',
  'divine', 'dix', 'dixon', 'doane', 'dobbs', 'dobson', 'dodge', 'dodson', 'doe', 'doggett',
  'dole', 'donaldson', 'donahue', 'donnell', 'donnelly', 'donovan', 'doolittle', 'doran', 'dorchester', 'dorman',
  'dorr', 'dorrance', 'dorsey', 'doty', 'doubleday', 'dougherty', 'douglas', 'douglass', 'dow', 'dowling',
  'downer', 'downes', 'downing', 'downs', 'dowse', 'doyle', 'drake', 'draper', 'drayton', 'dresser',
  'drew', 'drinker', 'driscoll', 'drown', 'drummond', 'drury', 'dryden', 'duane', 'dubois', 'dudley',
  'duer', 'duff', 'duffy', 'dugan', 'dummer', 'dumont', 'dunbar', 'duncan', 'dunham', 'dunlap',
  'dunn', 'dunning', 'dunphy', 'dunton', 'durand', 'durant', 'durfee', 'durham', 'durkee', 'durrell',
  'dustin', 'dutton', 'duval', 'dwight', 'dwyer', 'dyckman', 'dye', 'dyer', 'eager', 'eames',
  'earl', 'earle', 'early', 'eastman', 'easton', 'eaton', 'eberhardt', 'eckert', 'eddy', 'edes',
  'edgar', 'edgarton', 'edgerton', 'edison', 'edmonds', 'edmunds', 'edson', 'edwards', 'eells', 'egan',
  'egbert', 'eggleston', 'elder', 'eldredge', 'eldred', 'eldridge', 'eliot', 'elkins', 'ellery', 'ellet',
  'ellicott', 'elliot', 'elliott', 'ellis', 'ellison', 'ellsworth', 'elmer', 'elmes', 'elmore', 'elwell',
  'ely', 'emerson', 'emery', 'emmet', 'emmons', 'endicott', 'english', 'ennis', 'eno', 'enos',
  'ensign', 'eppes', 'erskine', 'ervin', 'estabrook', 'estes', 'etheridge', 'eustis', 'evans', 'evarts',
  'eveleth', 'everett', 'everit', 'everts', 'ewing', 'eyre', 'fabbri', 'fabian', 'fagan', 'fahnestock',
  'fairbank', 'fairbanks', 'fairchild', 'fairfax', 'fairfield', 'fairman', 'fales', 'fancher', 'fanning', 'farley',
  'farmer', 'farnam', 'farnham', 'farnsworth', 'farnum', 'farr', 'farrar', 'farrell', 'farrington', 'farwell',
  'fassett', 'faulkner', 'fawcett', 'faxon', 'fay', 'fearing', 'fellows', 'felton', 'fenner', 'fenton',
  'fenwick', 'ferguson', 'fernandez', 'fernold', 'ferris', 'ferry', 'fessenden', 'field', 'fields', 'fifield',
  'filley', 'fillmore', 'finch', 'finley', 'finn', 'finney', 'fish', 'fisher', 'fisk', 'fiske',
  'fitch', 'fithian', 'fitts', 'fitzgerald', 'fitzhugh', 'fitzpatrick', 'fitzsimmons', 'flagg', 'flanagan', 'flanders',
  'flannery', 'fleet', 'fleming', 'fletcher', 'flint', 'flood', 'flower', 'flowers', 'floyd', 'flynn',
  'fogg', 'folger', 'folsom', 'folwell', 'foote', 'forbes', 'force', 'ford', 'fordham', 'foreman',
  'forest', 'forman', 'forrest', 'forsaith', 'forsyth', 'fort', 'fosdick', 'foss', 'foster', 'foulke',
  'fowler', 'fox', 'frame', 'francis', 'frank', 'franklin', 'frary', 'fraser', 'frazer', 'frazier',
  'freeland', 'freeman', 'freer', 'french', 'fretz', 'frink', 'frisbie', 'frost', 'frothingham', 'fry',
  'frye', 'fuller', 'fullerton', 'fulton', 'furman', 'furness', 'gage', 'gaillard', 'gale', 'gallagher',
  'gallatin', 'galloway', 'gallup', 'galpin', 'gammell', 'gannett', 'gannon', 'ganson', 'gardiner', 'gardner',
  'garfield', 'garland', 'garner', 'garnett', 'garnsey', 'garretson', 'garrett', 'garrison', 'garry', 'gary',
  'gaskill', 'gaston', 'gates', 'gaunt', 'gay', 'gaylord', 'geary', 'gedney', 'gee', 'geer',
  'george', 'gerard', 'gerry', 'getman', 'gibbon', 'gibbons', 'gibbs', 'gibson', 'giddings', 'gifford',
  'gilbert', 'gilchrist', 'gilder', 'giles', 'gill', 'gillespie', 'gillett', 'gillette', 'gillis', 'gillman',
  'gilman', 'gilmore', 'gilpin', 'gilroy', 'girdler', 'givan', 'gladding', 'gladwin', 'glasgow', 'glass',
  'glazier', 'gleason', 'glenn', 'glidden', 'glover', 'glynn', 'goddard', 'godfrey', 'goff', 'gold',
  'goldsmith', 'goldthwaite', 'goodale', 'goodell', 'goodhue', 'goodman', 'goodrich', 'goodridge', 'goodsell', 'goodspeed',
  'goodwin', 'goodyear', 'gookin', 'gordon', 'gore', 'gorham', 'gorton', 'goss', 'gott', 'gould',
  'gove', 'gowen', 'gracie', 'grady', 'graff', 'grafton', 'graham', 'granger', 'grant', 'graves',
  'gray', 'greeley', 'green', 'greene', 'greenleaf', 'greenman', 'greenough', 'greenwood', 'greer', 'gregg',
  'gregory', 'grennell', 'gridley', 'grrier', 'griffin', 'griffith', 'griggs', 'grimes', 'grinnell', 'griswold',
  'groesbeck', 'gross', 'grosvenor', 'grout', 'grover', 'groves', 'grow', 'grubb', 'guernsey', 'guild',
  'guion', 'gulliver', 'gunn', 'gunther', 'gurney', 'guthrie', 'guy', 'gwynn', 'habersham', 'hacker',
  'hackett', 'hadley', 'hagar', 'hagen', 'hager', 'hagerty', 'haggerty', 'hague', 'hahn', 'haigh',
  'haines', 'haldeman', 'hale', 'haley', 'hall', 'hallet', 'hallett', 'hallock', 'hallowell', 'halsey',
  'halstead', 'ham', 'hamill', 'hamilton', 'hamlin', 'hamm', 'hammet', 'hammett', 'hammond', 'hampton',
  'hancock', 'hand', 'handy', 'hanford', 'hankins', 'hanks', 'hanley', 'hanna', 'hannah', 'hanscom',
  'hansen', 'hanson', 'hapgood', 'haraden', 'harbaugh', 'harding', 'hardwick', 'hardy', 'hare', 'hargraves',
  'harkness', 'harlan', 'harlow', 'harmon', 'harnden', 'harney', 'harper', 'harrell', 'harrington', 'harris',
  'harrison', 'hart', 'hartley', 'hartshorn', 'hartwell', 'harvey', 'harwood', 'hasbrouck', 'hascall', 'haskell',
  'haskins', 'hastings', 'hatch', 'hatcher', 'hathaway', 'hathorne', 'hauck', 'haven', 'havens', 'haverly',
  'haviland', 'hawes', 'hawkins', 'hawks', 'hawley', 'hawthorne', 'hay', 'hayden', 'hayes', 'hayman',
  'hayne', 'haynes', 'hays', 'hayward', 'hazard', 'hazel', 'hazelton', 'hazen', 'hazlett', 'head',
  'headley', 'heald', 'healy', 'heard', 'hearn', 'heath', 'heaton', 'hebbard', 'hedge', 'hedges',
  'heffernan', 'hegeman', 'heilman', 'heintz', 'heisler', 'heiss', 'helme', 'helm', 'helms', 'hemenway',
  'hemingway', 'hempstead', 'hendee', 'henderson', 'hendrick', 'hendricks', 'hendrickson', 'hendrix', 'henley', 'henn',
  'hennessy', 'henning', 'henry', 'hensley', 'henson', 'herbert', 'herman', 'herndon', 'herrick', 'herring',
  'herron', 'hersey', 'hershey', 'hervey', 'hess', 'hester', 'hewes', 'hewett', 'hewitt', 'hewlett',
  'hexton', 'heyward', 'heywood', 'hibbard', 'hickey', 'hickman', 'hickok', 'hicks', 'hidden', 'higbee',
  'higby', 'higgins', 'higginson', 'high', 'hight', 'hildreth', 'hiler', 'hill', 'hiller', 'hilliard',
  'hillman', 'hills', 'hillyer', 'hilton', 'hinckley', 'hinds', 'hine', 'hines', 'hinkle', 'hinman',
  'hinsdale', 'hinton', 'hitchcock', 'hitchings', 'hite', 'hoadley', 'hoag', 'hoagland', 'hoar', 'hobart',
  'hobbs', 'hobson', 'hodge', 'hodges', 'hodgkins', 'hodgman', 'hodgson', 'hoff', 'hoffman', 'hogan',
  'hoge', 'hogg', 'hoit', 'holbrook', 'holcomb', 'holcombe', 'holden', 'holder', 'holland', 'hollenbeck',
  'holley', 'holliday', 'hollingsworth', 'hollins', 'hollis', 'hollister', 'holloway', 'holly', 'holman', 'holmes',
  'holt', 'holton', 'holyoke', 'homans', 'homer', 'homes', 'honeywell', 'hood', 'hooker', 'hooper',
  'hoover', 'hope', 'hopkins', 'hopkinson', 'hopper', 'hoppin', 'hopson', 'horan', 'horn', 'horne',
  'horner', 'horsford', 'horton', 'hosford', 'hoskins', 'hosmer', 'hotchkiss', 'hough', 'houghton', 'house',
  'houston', 'hovey', 'howard', 'howe', 'howell', 'howes', 'howland', 'howlett', 'hoyt', 'hubbard',
  'hubbell', 'huber', 'huddleston', 'hudson', 'huet', 'huff', 'hughes', 'hughson', 'hulbert', 'hull',
  'hulse', 'humiston', 'humphrey', 'humphreys', 'humphries', 'hungerford', 'hunn', 'hunnewell', 'hunt', 'hunter',
  'huntington', 'huntley', 'huntoon', 'hurd', 'hurlburt', 'hurlbut', 'hurley', 'hurst', 'hussey', 'husted',
  'huston', 'hutchings', 'hutchins', 'hutchinson', 'hutton', 'hyatt', 'hyde', 'hyer', 'hyland', 'hyndman',
  'ide', 'ilsley', 'ingalls', 'ingersoll', 'ingham', 'ingraham', 'ingram', 'inman', 'ireland', 'irish',
  'irvin', 'irvine', 'irving', 'irwin', 'isaacs', 'isbell', 'isham', 'isom', 'ives', 'ivins',
  'jack', 'jackson', 'jacobs', 'jacobson', 'jacobus', 'jacques', 'jaeger', 'jagger', 'james', 'jameson',
  'jamieson', 'jamison', 'janes', 'janney', 'janvrin', 'jaques', 'jaquith', 'jarrett', 'jarvis', 'jay',
  'jayne', 'jeffers', 'jefferson', 'jeffery', 'jeffrey', 'jeffries', 'jelley', 'jencks', 'jenkins', 'jenks',
  'jenness', 'jenney', 'jennings', 'jennison', 'jerome', 'jervis', 'jessup', 'jewell', 'jewett', 'johns',
  'johnson', 'johnston', 'johnstone', 'jolley', 'jones', 'jordan', 'joslin', 'joslyn', 'josselyn', 'jouett',
  'joy', 'joyce', 'joyner', 'judd', 'judkins', 'judson', 'juilliard', 'julian', 'june', 'justis',
  'kane', 'kasson', 'kaufman', 'kavanaugh', 'kay', 'kean', 'keane', 'kearney', 'keasbey', 'keating',
  'keator', 'keeler', 'keeley', 'keen', 'keene', 'keeney', 'keep', 'keese', 'kehoe', 'keith',
  'kellar', 'keller', 'kelley', 'kellogg', 'kelly', 'kelsey', 'kelso', 'kemble', 'kemp', 'kemper',
  'kendall', 'kendrick', 'kenna', 'kennard', 'kennedy', 'kenney', 'kennon', 'kent', 'kenyon', 'keogh',
  'kerley', 'kern', 'kerr', 'ketcham', 'ketchum', 'keyes', 'keys', 'keyser', 'kibbe', 'kidd',
  'kidder', 'kidney', 'kilbourne', 'kilburn', 'kilduff', 'kilgore', 'killam', 'kilmer', 'kilpatrick', 'kimball',
  'kimberly', 'kincaid', 'king', 'kingman', 'kingsbury', 'kingsley', 'kinne', 'kinney', 'kinsley', 'kinsman',
  'kipling', 'kirby', 'kirk', 'kirkham', 'kirkland', 'kirkpatrick', 'kirkwood', 'kissam', 'kitchell', 'kitchen',
  'kittle', 'kittredge', 'klein', 'knapp', 'kneeland', 'knickerbocker', 'knight', 'knott', 'knowles', 'knowlton',
  'knox', 'koch', 'kohl', 'kollock', 'koon', 'koons', 'kountze', 'krueger', 'kuhn', 'kunkel',
  'kyle', 'labaree', 'lacey', 'lackey', 'lacombe', 'lacy', 'ladd', 'ladue', 'laflin', 'lafleur',
  'lahey', 'laidlaw', 'laird', 'lake', 'lally', 'lamb', 'lambert', 'lamont', 'lamoreaux', 'lamson',
  'lanahan', 'lancaster', 'land', 'lander', 'landers', 'landis', 'landon', 'lane', 'lang', 'langdon',
  'langford', 'langley', 'langston', 'langworthy', 'lanier', 'lanning', 'lanpher', 'lansing', 'lapham', 'larkin',
  'larned', 'larue', 'latham', 'lathrop', 'latimer', 'latrobe', 'laughlin', 'law', 'lawler', 'lawrence',
  'lawson', 'lawton', 'lay', 'layton', 'leach', 'leahy', 'leake', 'learned', 'leary', 'leavitt',
  'leaycraft', 'lebaron', 'lecompte', 'ledoux', 'ledyard', 'lee', 'leech', 'leeds', 'leete', 'lefferts',
  'leffingwell', 'leffler', 'leggett', 'lehigh', 'leighton', 'leland', 'leman', 'lemmon', 'lemon', 'lenox',
  'lent', 'leonard', 'leroy', 'lesley', 'leslie', 'lester', 'leverett', 'leverich', 'levis', 'levy',
  'lewis', 'libbey', 'libby', 'light', 'lightfoot', 'lillie', 'lilly', 'lincoln', 'lindley', 'lindsay',
  'lindsey', 'lines', 'linn', 'linsley', 'linton', 'lippincott', 'lippitt', 'lispenard', 'litchfield', 'littell',
  'little', 'littlefield', 'livermore', 'livingston', 'lloyd', 'lobdell', 'locke', 'lockhart', 'lockwood', 'lodge',
  'loeb', 'logan', 'lombard', 'long', 'longfellow', 'longley', 'longstreet', 'longworth', 'loomis', 'lord',
  'lorentz', 'lorillard', 'loring', 'lothrop', 'lott', 'loud', 'louden', 'loughran', 'lounsbury', 'love',
  'lovejoy', 'loveland', 'lovell', 'lovering', 'lovett', 'low', 'lowe', 'lowell', 'lowery', 'lowndes',
  'lowrey', 'lowry', 'loy', 'lozano', 'lucas', 'luce', 'luckey', 'ludington', 'ludlam', 'ludlow',
  'ludlum', 'lufkin', 'luke', 'lull', 'lummis', 'lumpkin', 'lunt', 'lupton', 'lusk', 'luther',
  'lyall', 'lybrand', 'lyford', 'lyman', 'lynch', 'lynde', 'lyndon', 'lyne', 'lynn', 'lyon',
  'lyons', 'lytle', 'mabie', 'macarthur', 'macaulay', 'macbride', 'maccallum', 'maccarthy', 'macclellan', 'macconnell',
  'maccormick', 'maccoy', 'maccrea', 'maccullough', 'macdonald', 'macdougal', 'macdougall', 'macdowell', 'mace', 'macfadden',
  'macfarland', 'macfarlane', 'macgill', 'macgowan', 'macgregor', 'machin', 'macintosh', 'macintyre', 'mack', 'mackay',
  'mackenzie', 'mackey', 'mackie', 'mackin', 'mackinnon', 'mackintosh', 'macknight', 'maclaren', 'maclaughlin', 'maclean',
  'macleish', 'macleod', 'macmahon', 'macmanus', 'macmillan', 'macmullen', 'macmurray', 'macnab', 'macnair', 'macnamara',
  'macnaughton', 'macneil', 'macneill', 'macomb', 'macpherson', 'macquarrie', 'macrae', 'macready', 'macveagh', 'macvicar',
  'macy', 'madden', 'maddock', 'madison', 'magee', 'magie', 'magill', 'magner', 'magoon', 'magruder',
  'maguire', 'mahan', 'maher', 'mahon', 'mahoney', 'main', 'mair', 'maitland', 'major', 'malcolm',
  'mallett', 'mallory', 'malone', 'maloney', 'maltby', 'man', 'manchester', 'mandeville', 'manley', 'mann',
  'manning', 'mansfield', 'manson', 'manthorne', 'manton', 'manville', 'mapes', 'marble', 'march', 'marcy',
  'marden', 'maris', 'markham', 'marks', 'marley', 'marlin', 'marlowe', 'marquand', 'marquardt', 'marquez',
  'marr', 'marrell', 'marsh', 'marshall', 'marston', 'martin', 'martindale', 'martinez', 'martyn', 'marvin',
  'mason', 'masters', 'masterson', 'mather', 'matheson', 'mathews', 'mathewson', 'matlack', 'matson', 'mattern',
  'matthews', 'matthewson', 'mattison', 'mattoon', 'maverick', 'maxcy', 'maxfield', 'maxon', 'maxwell', 'may',
  'mayer', 'mayhew', 'maynard', 'mayo', 'mays', 'mcalister', 'mcallister', 'mcalpin', 'mcaneny', 'mcardle',
  'mccabe', 'mccafferty', 'mccaffrey', 'mccagg', 'mccall', 'mccallum', 'mccann', 'mccarren', 'mccarroll', 'mccartan',
  'mccarthy', 'mccarty', 'mccauley', 'mccawley', 'mcchesney', 'mcclain', 'mcclary', 'mcclean', 'mcclellan', 'mcclelland',
  'mcclintock', 'mccloskey', 'mccloud', 'mcclung', 'mcclure', 'mccollum', 'mccomb', 'mcconnell', 'mccook', 'mccord',
  'mccormack', 'mccormick', 'mccosh', 'mccoy', 'mccracken', 'mccrea', 'mccready', 'mccreery', 'mccue', 'mcculloch',
  'mccullough', 'mccune', 'mccurdy', 'mccutcheon', 'mcdaniel', 'mcdermott', 'mcdonald', 'mcdonnell', 'mcdonough', 'mcdougal',
  'mcdougall', 'mcdowell', 'mcelroy', 'mcfadden', 'mcfarland', 'mcfarlane', 'mcgarrah', 'mcgee', 'mcgill', 'mcginley',
  'mcginnis', 'mcglone', 'mcgovern', 'mcgowan', 'mcgrath', 'mcgraw', 'mcgregor', 'mcguire', 'mchenry', 'mcilvaine',
  'mcindoe', 'mcintosh', 'mcintyre', 'mciver', 'mckay', 'mckean', 'mckee', 'mckeen', 'mckellar', 'mckenna',
  'mckenney', 'mckenzie', 'mckeon', 'mckim', 'mckinley', 'mckinney', 'mckinstry', 'mcknight', 'mclain', 'mclane',
  'mclaren', 'mclaughlin', 'mclean', 'mclellan', 'mcleod', 'mcloughlin', 'mcmahon', 'mcmaster', 'mcmichael', 'mcmillan',
  'mcmullen', 'mcmurray', 'mcnab', 'mcnair', 'mcnally', 'mcnamara', 'mcnamee', 'mcnaught', 'mcneil', 'mcneill',
  'mcnulty', 'mcpherson', 'mcquade', 'mcqueen', 'mcrae', 'mcvickar', 'mcwilliams', 'mead', 'meade', 'meador',
  'meadows', 'meagher', 'means', 'mears', 'meeker', 'meeks', 'megrue', 'meigs', 'mellen', 'mellon',
  'melville', 'melvin', 'mendenhall', 'mercer', 'merchant', 'meredith', 'meriam', 'merivale', 'meriwether', 'merrell',
  'merriam', 'merrick', 'merrill', 'merriman', 'merritt', 'merry', 'mervine', 'meserole', 'meserve', 'messenger',
  'metcalf', 'metcalfe', 'meyer', 'meyers', 'michael', 'michell', 'mickle', 'middleton', 'mifflin', 'milbank',
  'milburn', 'miles', 'millard', 'miller', 'millet', 'millett', 'milligan', 'milliken', 'mills', 'milne',
  'milner', 'milton', 'miner', 'minot', 'minton', 'minturn', 'mitchel', 'mitchell', 'mix', 'mixer',
  'moen', 'moffat', 'moffett', 'moffit', 'mohr', 'moir', 'molineux', 'moll', 'monell', 'monroe',
  'montague', 'montgomery', 'moody', 'moon', 'mooney', 'moore', 'moorhead', 'moran', 'more', 'morehead',
  'morehouse', 'morerell', 'morgan', 'morley', 'morrell', 'morrill', 'morris', 'morrison', 'morrow', 'morse',
  'mortimer', 'morton', 'moseley', 'moser', 'moses', 'mosher', 'moss', 'mott', 'moulton', 'mount',
  'mowry', 'moyer', 'mudge', 'muir', 'mulford', 'mullan', 'mulligan', 'mullin', 'mullins', 'mulock',
  'mumford', 'munger', 'munn', 'munro', 'munroe', 'munsell', 'munson', 'murdock', 'murphy', 'murray',
  'musgrave', 'mutter', 'myers', 'mygatt', 'myrick', 'nagel', 'nancarrow', 'napier', 'nash', 'nason',
  'naylor', 'neal', 'neale', 'neally', 'needham', 'neff', 'neil', 'neill', 'neilson', 'nelson',
  'nesbit', 'nesmith', 'nettleton', 'neville', 'nevin', 'nevins', 'newberry', 'newcomb', 'newell', 'newhall',
  'newkirk', 'newland', 'newlin', 'newman', 'newton', 'nicholas', 'nicholl', 'nicholls', 'nichols', 'nicholson',
  'nickerson', 'nicoll', 'niles', 'nimmo', 'nims', 'niven', 'nixon', 'noble', 'noel', 'nolan',
  'noonan', 'norcross', 'norman', 'norris', 'north', 'northrop', 'norton', 'norvell', 'norwood', 'nott',
  'nowell', 'noyes', 'nugent', 'nunn', 'nutting', 'nye', 'oakes', 'oakley', 'oaks', 'ober',
  'obrien', 'obryon', 'ocallaghan', 'oconnell', 'oconnor', 'odell', 'odiorne', 'odonnell', 'odonovan', 'ogden',
  'ogilvie', 'ogle', 'oglesby', 'ohara', 'ohare', 'okeefe', 'olcott', 'oldham', 'olds', 'oliphant',
  'oliver', 'olmstead', 'olmsted', 'olney', 'oneal', 'oneil', 'oneill', 'opdyke', 'ordway', 'ormond',
  'ormsby', 'orr', 'ortiz', 'orton', 'osborn', 'osborne', 'osgood', 'oshea', 'osman', 'ostrom',
  'otis', 'otman', 'outerbridge', 'overton', 'owen', 'owens', 'oxnard', 'packard', 'packer', 'paddock',
  'padelford', 'page', 'paige', 'paine', 'painter', 'palen', 'palfray', 'palmer', 'pancoast', 'pangborn',
  'panton', 'papin', 'pardee', 'parish', 'park', 'parke', 'parker', 'parkhurst', 'parkman', 'parks',
  'parmelee', 'parmenter', 'parris', 'parrish', 'parrott', 'parry', 'parsons', 'partridge', 'paschall', 'patch',
  'patchin', 'paton', 'patrick', 'pattee', 'patten', 'patterson', 'pattison', 'patton', 'paul', 'paulding',
  'paull', 'paxton', 'payne', 'paynter', 'payson', 'peabody', 'peacock', 'peale', 'pearce', 'pearl',
  'pearman', 'pearsall', 'pearson', 'pease', 'peaslee', 'peck', 'peckham', 'pedrick', 'peebles', 'peek',
  'peet', 'pegram', 'peirce', 'pelham', 'pell', 'pelton', 'pemberton', 'pendergast', 'pendleton', 'penfield',
  'penhallow', 'penn', 'pennell', 'penney', 'penniman', 'pennington', 'pennock', 'pennoyer', 'penrose', 'perce',
  'percy', 'perham', 'perit', 'perkins', 'perley', 'perot', 'perrin', 'perrine', 'perry', 'peters',
  'petersen', 'peterson', 'pethick', 'pettee', 'pettengill', 'pettibone', 'pettigrew', 'pettingill', 'pettis', 'pettit',
  'pettus', 'petty', 'pew', 'pfaelzer', 'phelps', 'philbrick', 'philbrook', 'philips', 'phillips', 'phinney',
  'phipps', 'phoenix', 'pickard', 'pickens', 'pickering', 'pickett', 'pickman', 'pierce', 'pierpont', 'pierrepont',
  'pierson', 'piggott', 'pike', 'pillsbury', 'pinckney', 'pine', 'pingree', 'pinkerton', 'pinkney', 'pinney',
  'piper', 'pitkin', 'pitman', 'pitt', 'pitts', 'pixley', 'place', 'plant', 'platt', 'pleasanton',
  'plimpton', 'plumb', 'plumer', 'plumley', 'plummer', 'plunkett', 'poe', 'poindexter', 'poland', 'polhemus',
  'polk', 'pollard', 'pollock', 'pomeroy', 'pomfret', 'pond', 'pool', 'poole', 'poor', 'poore',
  'pope', 'porter', 'post', 'potter', 'potts', 'pound', 'powel', 'powell', 'power', 'powers',
  'pratt', 'preble', 'prentice', 'prentiss', 'prescott', 'preston', 'price', 'priest', 'prime', 'prince',
  'prior', 'pritchard', 'proctor', 'prouty', 'pruyn', 'puffer', 'pugh', 'pugsley', 'pulitzer', 'pulleyn',
  'pullman', 'pulsifer', 'pumphrey', 'purcell', 'purdy', 'purinton', 'purmort', 'purnell', 'purrington', 'purves',
  'purviance', 'purvis', 'putnam', 'putney', 'pyne', 'quackenbush', 'quarles', 'quay', 'quayle', 'quealy',
  'queen', 'quigley', 'quimby', 'quinby', 'quincy', 'quinlan', 'quinn', 'quintard', 'quinton', 'rabe',
  'radcliff', 'radcliffe', 'rae', 'rafferty', 'rainier', 'rains', 'ralston', 'ramsay', 'ramsey', 'rand',
  'randall', 'randolph', 'rankin', 'ranney', 'ranson', 'rathbone', 'rathbun', 'rawle', 'rawlings', 'rawson',
  'ray', 'raymond', 'rayner', 'rea', 'read', 'reade', 'reading', 'reagan', 'rector', 'redfield',
  'redington', 'redman', 'redmond', 'reed', 'reeder', 'reese', 'reeve', 'reeves', 'reid', 'reilly',
  'reinhart', 'remington', 'remsen', 'renwick', 'revere', 'reynolds', 'rhea', 'rhinelander', 'rhoades', 'rhodes',
  'rice', 'rich', 'richard', 'richards', 'richardson', 'richmond', 'ricker', 'ricketson', 'ricketts', 'rickman',
  'riddle', 'rider', 'ridgely', 'ridgway', 'riggs', 'riker', 'riley', 'rinehart', 'ring', 'ripley',
  'risley', 'ritchie', 'rittenhouse', 'ritter', 'rivers', 'rix', 'roach', 'roane', 'robb', 'robbins',
  'roberts', 'robertson', 'robie', 'robins', 'robinson', 'robison', 'roby', 'roche', 'rockefeller', 'rockwell',
  'rockwood', 'rodgers', 'rodman', 'rodney', 'roe', 'roebling', 'rogers', 'rohlfs', 'roland', 'rollins',
  'rolston', 'romaine', 'romeo', 'romeyn', 'rood', 'rooke', 'rooney', 'roosevelt', 'root', 'ropes',
  'rose', 'rosenfeld', 'ross', 'rosser', 'rossiter', 'rothschild', 'roundy', 'rouse', 'rowan', 'rowe',
  'rowell', 'rowland', 'rowley', 'roy', 'royal', 'royce', 'royle', 'royster', 'rudd', 'ruddock',
  'rudolph', 'ruffin', 'rugg', 'ruggles', 'rumsey', 'rundle', 'runyon', 'rupert', 'rush', 'rushmore',
  'russ', 'russell', 'rust', 'rutherford', 'rutledge', 'ryan', 'ryder', 'ryerson', 'sabin', 'sackett',
  'sadler', 'safford', 'sage', 'salisbury', 'salmon', 'salter', 'saltonstall', 'sampson', 'samson', 'samuels',
  'sanborn', 'sanders', 'sanderson', 'sands', 'sanford', 'sanger', 'sargent', 'satterlee', 'satterthwaite', 'satterwhite',
  'saunders', 'savage', 'savery', 'saville', 'sawyer', 'saxton', 'sayre', 'scammon', 'scammell', 'schaeffer',
  'schell', 'schenck', 'schermerhorn', 'schieffelin', 'schiller', 'schley', 'schmidt', 'schneider', 'schofield', 'schoonmaker',
  'schott', 'schroeder', 'schultz', 'schuyler', 'schwab', 'schwartz', 'scofield', 'scott', 'scoville', 'scranton',
  'scribner', 'scudder', 'scull', 'sealy', 'seaman', 'seamans', 'searing', 'searle', 'sears', 'seaton',
  'seaver', 'seavey', 'seawell', 'sedgwick', 'seeley', 'seely', 'seelye', 'sefton', 'seger', 'segur',
  'seibert', 'selby', 'selden', 'selfridge', 'seligman', 'selleck', 'sellers', 'selover', 'semple', 'seney',
  'sergeant', 'sessions', 'severance', 'sevier', 'sewall', 'seward', 'sewell', 'sexton', 'seymour', 'shackelford',
  'shaffer', 'shafter', 'shaler', 'shane', 'shannon', 'sharon', 'sharp', 'sharpe', 'shattuck', 'shaw',
  'shea', 'sheafe', 'shedd', 'sheehan', 'sheffield', 'shelby', 'sheldon', 'shelley', 'shelton', 'shepard',
  'shepherd', 'shepley', 'sheppard', 'sheridan', 'sherman', 'sherrill', 'sherwin', 'sherwood', 'shields', 'shillaber',
  'shipley', 'shipman', 'shippen', 'shirley', 'shoemaker', 'shore', 'shores', 'short', 'shreve', 'shufeldt',
  'shumway', 'shurtleff', 'shute', 'sibley', 'sickles', 'sigourney', 'sikes', 'sill', 'silliman', 'silsbee',
  'silva', 'silver', 'simmons', 'simms', 'simonds', 'simons', 'simonson', 'simonton', 'simpkins', 'simpson',
  'sims', 'sinclair', 'singer', 'singleton', 'sinnott', 'sisson', 'skelton', 'skidmore', 'skiff', 'skinner',
  'slack', 'slade', 'slater', 'slattery', 'slaughter', 'slawson', 'sleeper', 'sloan', 'sloane', 'slocum',
  'slosson', 'small', 'smalley', 'smart', 'smedley', 'smiley', 'smith', 'smithson', 'smock', 'smyser',
  'smyth', 'smythe', 'snell', 'snelling', 'snow', 'snowden', 'snyder', 'somers', 'somerville', 'sooy',
  'soper', 'soule', 'southard', 'southerland', 'southgate', 'southmayd', 'southwick', 'southworth', 'soutter', 'spader',
  'spafford', 'spalding', 'spangler', 'sparks', 'sparrow', 'spaulding', 'spear', 'spears', 'speed', 'speer',
  'spellman', 'spence', 'spencer', 'sperry', 'spicer', 'spies', 'spofford', 'spooner', 'sprague', 'spratt',
  'spring', 'springer', 'sproul', 'sproule', 'spry', 'squires', 'stacy', 'stafford', 'stagg', 'stahl',
  'staley', 'standish', 'stanfield', 'stanford', 'stanhope', 'stanley', 'stannard', 'stanton', 'staples', 'starbuck',
  'stark', 'starkey', 'starks', 'starkweather', 'starr', 'starrett', 'stauffer', 'stearns', 'stebbins', 'stedman',
  'steel', 'steele', 'steers', 'steffen', 'stein', 'steiner', 'steinmetz', 'steinway', 'stephens', 'stephenson',
  'sterling', 'stern', 'stetson', 'steven', 'stevens', 'stevenson', 'steward', 'stewart', 'stickney', 'stiles',
  'stillman', 'stillwell', 'stilwell', 'stimson', 'stinson', 'stirling', 'stjohn', 'stocking', 'stockton', 'stockwell',
  'stoddard', 'stoddart', 'stokes', 'stone', 'storer', 'storey', 'storm', 'storrs', 'story', 'stott',
  'stoughton', 'stout', 'stover', 'stow', 'stowe', 'stowell', 'strait', 'stranahan', 'strange', 'stratton',
  'straus', 'strauss', 'street', 'streeter', 'strickland', 'strong', 'stroud', 'stryker', 'stuart', 'sturdevant',
  'sturges', 'sturgis', 'sturtevant', 'stuyvesant', 'sullivan', 'summers', 'sumner', 'sutherland', 'sutphen', 'sutphin',
  'sutton', 'suydam', 'swain', 'swan', 'swartout', 'swartwout', 'swartz', 'swayze', 'sweeney', 'sweet',
  'sweetser', 'swenson', 'swett', 'swift', 'swinburne', 'swing', 'swinton', 'swords', 'sykes', 'sylvester',
  'symmes', 'symonds', 'symons', 'taber', 'taft', 'taggart', 'talbot', 'talcott', 'taliaferro', 'tallmadge',
  'tallman', 'talmadge', 'talmage', 'tanner', 'tapley', 'tappan', 'tarbell', 'tarbox', 'tate', 'taylor',
  'teall', 'teasdale', 'tefft', 'temple', 'templeton', 'tenbroeck', 'teneyck', 'tennant', 'tenney', 'terhune',
  'terrell', 'terrill', 'terry', 'thacher', 'thackeray', 'thalberg', 'thatcher', 'thaxter', 'thayer', 'theobald',
  'thomas', 'thompson', 'thomson', 'thorndike', 'thorne', 'thornton', 'thorp', 'thorpe', 'thrall', 'thurber',
  'thurlow', 'thurman', 'thurston', 'tibbetts', 'tibbits', 'tice', 'tichenor', 'ticknor', 'tiffany', 'tift',
  'tilden', 'tileston', 'tilford', 'tilghman', 'tillinghast', 'tillman', 'tillotson', 'tilton', 'timmons', 'tinker',
  'tisdale', 'titcomb', 'titus', 'tobey', 'tobias', 'tod', 'todd', 'tolman', 'tomkins', 'tomlinson',
  'tompkins', 'toomey', 'torrance', 'torrey', 'totten', 'toucey', 'tower', 'towle', 'town', 'towne',
  'townley', 'townsend', 'tracy', 'train', 'trask', 'traver', 'travers', 'travis', 'treadwell', 'treat',
  'tredwell', 'tremaine', 'trenchard', 'trevor', 'trimble', 'trippe', 'trollope', 'trott', 'trotter', 'trowbridge',
  'trudeau', 'true', 'truesdale', 'truesdell', 'truitt', 'truman', 'trumbull', 'tryon', 'tubb', 'tubbs',
  'tuck', 'tucker', 'tuckerman', 'tudor', 'tufts', 'tuller', 'tully', 'tupper', 'turck', 'turnbull',
  'turner', 'turnure', 'tuthill', 'tuttle', 'twining', 'twiss', 'twitchell', 'twombly', 'tyler', 'tyndall',
  'tyng', 'tyson', 'udall', 'ulmer', 'underhill', 'underwood', 'upham', 'upton', 'usher', 'utley',
  'vail', 'valentine', 'valleau', 'vallette', 'vanalstyne', 'vanantwerp', 'vanarsdale', 'vanbeuren', 'vanbrunt', 'vanburen',
  'vancortlandt', 'vancott', 'vanderbilt', 'vanderburgh', 'vanderhoof', 'vanderlip', 'vanderpoel', 'vanderpool', 'vanderveer', 'vandervoort',
  'vanderwerf', 'vandyke', 'vanetten', 'vanhorn', 'vanhouten', 'vankleeck', 'vanname', 'vanness', 'vannest', 'vannordstrand',
  'vannostrand', 'vanorden', 'vanpelt', 'vanrensselaer', 'vanschaick', 'vansiclen', 'vanslyke', 'vanslyke', 'vanvalkenburgh', 'vanvleck',
  'vanvliet', 'vanvoorhis', 'vanvorst', 'vanwagenen', 'vanwart', 'vanwyck', 'vanzandt', 'varick', 'varnum', 'vassar',
  'vaughan', 'vaughn', 'veazey', 'vedder', 'veeder', 'vermeule', 'vermilion', 'vernon', 'verplanck', 'very',
  'vial', 'viall', 'vickery', 'vidal', 'vieira', 'viele', 'vignaud', 'villas', 'vinal', 'vincent',
  'vining', 'vinton', 'visscher', 'vogel', 'volk', 'voorhees', 'voorhis', 'vose', 'vought', 'vredenburgh',
  'vroom', 'vrooman', 'waddell', 'waddy', 'wade', 'wadsworth', 'wager', 'wagner', 'wagstaff', 'wainwright',
  'wait', 'waite', 'wakefield', 'wakeman', 'walbridge', 'walcott', 'walden', 'walder', 'waldo', 'waldron',
  'wales', 'walker', 'wall', 'wallace', 'waller', 'walling', 'wallis', 'walmsley', 'walsh', 'walter',
  'walters', 'walton', 'walworth', 'wanamaker', 'warburton', 'ward', 'wardell', 'warden', 'wardwell', 'ware',
  'warfield', 'waring', 'warner', 'warren', 'warriner', 'washburn', 'washington', 'waterbury', 'waterhouse', 'waterman',
  'waters', 'watkins', 'watrous', 'watson', 'watt', 'watters', 'watts', 'waugh', 'way', 'wayne',
  'weaver', 'webb', 'webber', 'webster', 'weed', 'weeks', 'weems', 'weidman', 'weir', 'welch',
  'weld', 'weldon', 'weller', 'welles', 'wellington', 'wellman', 'wells', 'welsh', 'welton', 'wendell',
  'wentworth', 'wenzel', 'werner', 'wescott', 'wessel', 'wessels', 'west', 'westbrook', 'westcott', 'westervelt',
  'westing', 'weston', 'wetherbee', 'wetherell', 'wetherill', 'wetmore', 'whalen', 'wharton', 'wheatley', 'wheaton',
  'wheeler', 'wheelock', 'wheelwright', 'whelen', 'whinery', 'whipple', 'whitaker', 'whitcomb', 'white', 'whitehead',
  'whitehouse', 'whitelaw', 'whiteman', 'whiteside', 'whitfield', 'whitin', 'whiting', 'whitlock', 'whitman', 'whitmore',
  'whitney', 'whiton', 'whittaker', 'whittemore', 'whittier', 'whittingham', 'whittington', 'whittle', 'whittlesey', 'whyte',
  'wickes', 'wickham', 'wicks', 'wiggin', 'wiggins', 'wight', 'wightman', 'wilber', 'wilbor', 'wilbour',
  'wilbur', 'wilcox', 'wilcoxson', 'wild', 'wilde', 'wilder', 'wildes', 'wildman', 'wiles', 'wiley',
  'wilkes', 'wilkie', 'wilkins', 'wilkinson', 'willard', 'willcox', 'willets', 'willett', 'williams', 'williamson',
  'willis', 'williston', 'willits', 'willoughby', 'wills', 'wilmarth', 'wilmerding', 'wilmot', 'wilson', 'winans',
  'winch', 'winchester', 'windsor', 'wing', 'winne', 'winship', 'winslow', 'winsor', 'winston', 'winter',
  'winters', 'winthrop', 'wise', 'wisner', 'wiswall', 'witherbee', 'witherell', 'withers', 'witherspoon', 'witmer',
  'witt', 'wolcott', 'wolf', 'wolfe', 'wolff', 'wood', 'woodard', 'woodbridge', 'woodbury', 'woodcock',
  'woodford', 'woodhull', 'woodin', 'woodman', 'woodruff', 'woods', 'woodward', 'woodworth', 'wooley', 'woolsey',
  'woolworth', 'wooster', 'worcester', 'worden', 'work', 'workman', 'worley', 'wormley', 'worrall', 'worth',
  'worthington', 'worthy', 'wortman', 'wright', 'wyatt', 'wyckoff', 'wyeth', 'wylie', 'wyman', 'wynkoop',
  'wynn', 'wynne', 'yale', 'yancy', 'yard', 'yardley', 'yates', 'yeager', 'yeomans', 'yerkes',
  'york', 'yost', 'young', 'youngman', 'youngs', 'zabriskie', 'zane', 'ziegler', 'zimmerman', 'zonta'
]);

export const MOCK_MINERALS = new Set([
  'quartzo', 'ametista', 'topazio', 'rubi', 'safira', 'esmeralda', 'diamante',
  'granito', 'marmore', 'basalto', 'calcario', 'arenito', 'argila'
]);

export const MOCK_TECH = new Set([
  'cloud', 'server', 'host', 'app', 'soft', 'tech', 'data', 'cyber', 'net',
  'web', 'bot', 'ai', 'crypto', 'token', 'chain', 'block', 'node'
]);

// Sample data to preload if user doesn't have a file
export const SAMPLE_DOMAINS_TXT = `
casa.com.br
ap.com.br
123.com.br
a1.com.br
abc.com.br
xyz.com.br
loja.com.br
shop.com.br
gato.com.br
dog.com.br
rio.com.br
joao.com.br
silva.com.br
pereira.com.br
souza.net.br
oliveira.art.br
topazio.com.br
cloud.com.br
supertech.com.br
festa10.com.br
compreagora.com.br
verylongdomainnameinenglish.com.br
dominiomuitolongoportugues.com.br
qz8.com.br
7up.com.br
br.com.br
sp.com.br
alves.com.br
fernandes.com.br
menezes.com.br
vasconcelos.net.br
cavalcante.org.br
`;
